### ISSUE TITLE
Error in " window = app.Window()"

### ISSUE THREAD

**Issue by chaoshengt** [glumpy/glumpy#104]
when I run the code in Jupyter notebook
`%tb`
`from glumpy import app`
`window = app.Window()`
`app.run()`  

I get following error:  
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Anaconda3\lib\argparse.py in _get_value(self, action, arg_string)
   2285         try:
-> 2286             result = type_func(arg_string)
   2287 

ValueError: invalid literal for int() with base 10: 'C:\\Users\\tcs\\AppData\\Roaming\\jupyter\\runtime\\kernel-04bb4e56-fc80-4b72-af51-e602eb993e43.json'

During handling of the above exception, another exception occurred:

ArgumentError                             Traceback (most recent call last)
C:\Anaconda3\lib\argparse.py in parse_known_args(self, args, namespace)
   1757         try:
-> 1758             namespace, args = self._parse_known_args(args, namespace)
   1759             if hasattr(namespace, _UNRECOGNIZED_ARGS_ATTR):

C:\Anaconda3\lib\argparse.py in _parse_known_args(self, arg_strings, namespace)
   1963             # consume the next optional and any arguments for it
-> 1964             start_index = consume_optional(start_index)
   1965 

C:\Anaconda3\lib\argparse.py in consume_optional(start_index)
   1903             for action, args, option_string in action_tuples:
-> 1904                 take_action(action, args, option_string)
   1905             return stop

C:\Anaconda3\lib\argparse.py in take_action(action, argument_strings, option_string)
   1815             seen_actions.add(action)
-> 1816             argument_values = self._get_values(action, argument_strings)
   1817 

C:\Anaconda3\lib\argparse.py in _get_values(self, action, arg_strings)
   2256             arg_string, = arg_strings
-> 2257             value = self._get_value(action, arg_string)
   2258             self._check_value(action, value)

C:\Anaconda3\lib\argparse.py in _get_value(self, action, arg_string)
   2298             msg = _('invalid %(type)s value: %(value)r')
-> 2299             raise ArgumentError(action, msg % args)
   2300 

ArgumentError: argument --framerate/-f: invalid int value: 'C:\\Users\\tcs\\AppData\\Roaming\\jupyter\\runtime\\kernel-04bb4e56-fc80-4b72-af51-e602eb993e43.json'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
<ipython-input-1-4b81839fe6c8> in <module>()
      1 from glumpy import app
----> 2 window = app.Window()
      3 app.run()

C:\Anaconda3\lib\site-packages\glumpy\app\__init__.py in __new__(cls, *args, **kwargs)
    140 
    141         all = list(backends.__backends__)
--> 142         options = parser.get_options()
    143 
    144         # No backend was specified

C:\Anaconda3\lib\site-packages\glumpy\app\parser.py in get_options()
     29     """ Parse and retrun command line options. """
     30 
---> 31     options, unknown = get_default().parse_known_args()
     32     return options
     33 

C:\Anaconda3\lib\argparse.py in parse_known_args(self, args, namespace)
   1763         except ArgumentError:
   1764             err = _sys.exc_info()[1]
-> 1765             self.error(str(err))
   1766 
   1767     def _parse_known_args(self, arg_strings, namespace):

C:\Anaconda3\lib\argparse.py in error(self, message)
   2383         self.print_usage(_sys.stderr)
   2384         args = {'prog': self.prog, 'message': message}
-> 2385         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

C:\Anaconda3\lib\argparse.py in exit(self, status, message)
   2370         if message:
   2371             self._print_message(message, _sys.stderr)
-> 2372         _sys.exit(status)
   2373 
   2374     def error(self, message):

SystemExit: 2
 
![qq 20170223094220](https://cloud.githubusercontent.com/assets/7035642/23241163/88efd3e8-f9ac-11e6-9a59-e82d7f91178f.png)

**Comment by rougier** [comment]
Yes, glumpy is not (yet) compatible with the Jupyter notebook.
