### ISSUE TITLE
How to use separate shape and texture indices?

### ISSUE THREAD

**Issue by wpk-** [glumpy/glumpy#108]
I have a textured mesh with N shape vertices and M texture coordinates. There are T triangles for shape and for texture, but clearly the shape indices are different from the texture indices.

In the examples I can only find `prog.draw(GL_TRIANGLES, indices)`, which to me looks like I can only pass one IndexBuffer. How can I specify separate shape/texture indices?

**Comment by rougier** [comment]
Currently, you need to have different vertices when they have different texture coordinates (no shared texture coord, same for normals).

**Comment by rougier** [comment]
With later GL versions (I don't know which) you could do that I think, need to investigate.

**Comment by wpk-** [comment]
This article seems to agree with what you are saying: for OpenGL we have to duplicate the vertices. http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-9-vbo-indexing/

I'm completely surprised, but unpacking on the CPU is no problem. Thanks for your help!
