### ISSUE TITLE
Improper transformations related to protein.py

### ISSUE THREAD

**Issue by Ngtungfei** [glumpy/glumpy#115]
protein.py
Resizing windows and extremely zooming out  will cause improper transformations.

**Comment by rougier** [comment]
What kind of improper transformations ?

**Comment by Ngtungfei** [comment]
when resizing the width of window, the size of atoms changes inversely.

**Comment by rougier** [comment]
No, they keep the same size actually but because of window resizing, they are farther apart.

**Comment by Ngtungfei** [comment]
Thanks, Rougier.
It seem weird when resizing the width of window. Is it possible to achieve the same result with resizing the height of window.

**Comment by rougier** [comment]
Oh wait, resizing only height does not produce the weird transformation. I'll try to investigate.
