### ISSUE TITLE
How to embed glumpy in a Qt or Tkinter script?

### ISSUE THREAD

**Issue by Ngtungfei** [glumpy/glumpy#116]
Does glumpy have  Widgets e.g. Buttons, Entry etc?
Or can it be used as a Widget in Qt or Tkinter?

**Comment by rougier** [comment]
No, glumpy does not have widgets. It cannot be used with tkinter (because it does not support OpenGL)  but it is possible with Qt. An example would be useful actually if you're willing to help.
