### ISSUE TITLE
what is the elegant way to get depth?

### ISSUE THREAD

**Issue by liyi14** [glumpy/glumpy#119]
This repo is really awesome! It helps me a lot!
Just one question: is it possible for me to get the depth map while rendering the color image? 
I am trying to load a `.obj` model and get the rendered color image and the corresponding depth image of a  specific pose. 
I know I can build two `vertex` function, but just think it a bit clumsy since I have to draw two times. 
So will it be possible for me to get the color image and depth image simultaneously with a single draw?

**Comment by rougier** [comment]
You can but you need a framebuffer. Have a look at the protein-ssao.py example. I record the depth (and the color) into a texture that you can read later from within another shader or from the CPU if yu transfer it.

**Comment by liyi14** [comment]
It seems this line of code will get the depth image
`gl.glReadPixels(0, 0, self.width, self.height, gl.GL_DEPTH_COMPONENT, gl.GL_FLOAT, depth_buffer)`
Is it the right way?
