### ISSUE TITLE
What caused err 1281?

### ISSUE THREAD

**Issue by liyi14** [glumpy/glumpy#129]
Hi, 

Thanks for reading and happy new year!

I am trying to use glumpy in one of my layer in my network,
and I may have several instances of this layer in the network.
And I always get the message says when I implementing this layer and have to write it in an ugly way:

```
GLError: GLError(
	err = 1281,
	description = 'invalid value',
	baseOperation = glUseProgram,
	cArguments = (1L,)
)
```

The layer call a class Render_Py like this:
```
class Render_Py():
    def __init__(...):
        ...
        self.render_kernel = gloo.Program(vertex, fragment)
        self.window = app.Window(width=self.width, height=self.height, visiible=False)
        @self.window.event
        def on_draw(dt):
            self.window.clear()
            gl.glDisable(gl.GL_BLEND)
            gl.glEnable(gl.GL_DEPTH_TEST)
            self.render_kernel.draw(gl.GL_TRIANGLES)
            gl.glReadPixels(0, 0, self.width, self.height, gl.GL_RGBA, gl.GL_FLOAT, self.rgb_buffer)
            gl.glReadPixels(0, 0, self.width, self.height, gl.GL_DEPTH_COMPONENT, gl.GL_FLOAT, self.depth_buffer)
        @self.window.event
        def on_init():
            gl.glEnable(gl.GL_DEPTH_TEST)
        ...

    def render(...):
        ...
        self.render_kernel['u_view'] = self._get_view_mtx(R, t)
        app.run(framecount=0)
        rgb_gl = np.copy(self.rgb_buffer)
        depth_gl = np.copy(self.depth_buffer)
        ...

    def __del__(self):
        self.window.close()

```

And the layer in the network:
```
class batchUpdaterOperator(mx.operator.CustomOp):
    def __init__(...):
        ...
        # --- part A ----
        self.render_machine = Render_Py(self.model_dir, self.K, self.width, self.height, self.zNear, self.zFar)
        # -----------------
        self.reinit = True
        ...

     def forward(...):
          if self.reinit:
              # --- part B ----
              self.render_machine = Render_Py(self.model_dir, self.K, self.width, self.height, self.zNear, self.zFar)
              self.reinit = False
              # ----------------
           ...
           refined_image, refined_depth = self.render_machine.render(cur_pose[:3, :3], cur_pose[:3, 3])
           ...
```
When I use **more than one** instances of this layer in the network:

- If I only enable ```part A``` in the layer, I will get ```Error: Attempt to retrieve context when no valid context```
- If I only enable ``` part B``` in the layer, I will get the error 1281.
- However, if I enable ```part A``` and ```part B``` at the same time, it can run successfully if I train it on one GPU. (it will report error 1281 if I train it on multiple GPUs)

I am wondering what caused this error and why this strange operation can fix it, can you give me some suggestions?

PS: I can run the example app-two-windows without any problem.

Thanks!

**Comment by rougier** [comment]
I'm not sute I understand what you're trying to render. You have two opened windows and you want to render in each of one but you cannot render in only one window at a time. Is that correct ?

Would you have a minimal example showing the problem ?

Not related but you have a `visiible` instead of `visible`

**Comment by liyi14** [comment]
I don't know how to reproduce the problem without current deep learning framework.

I mean I have to render twice in each layer to make glumpy work, one at init and the other at the first forward, although **I only need one of them**.
It will report an error if I only create one of them.

**Comment by rougier** [comment]
Can you write a small demo that more or less follow your deep learning framework with dummy rendering just to test if the reason it doesn't work is the tow render calls?

**Comment by SunYangtian** [comment]
Hello! @liyi14 @rougier.  I meet the same question roughly the same with you.

It's OK to run the example app-two-windows, and I can open two windows as expected. And I can render successfully in each window separately. But if I try to use the draw function to render in both windows at the same time, it causes to error. Like the code below:

```
@window.event
def on_draw(dt):
    window.clear()
    cube.draw(gl.GL_TRIANGLES, I)

@window2.event
def on_draw(dt):
    window2.clear()
    cube2.draw(gl.GL_TRIANGLES, I)
```
To be more specific, if I use `cube.draw` in `window` and `cube2.draw` in `window2`, the error code of GLError is 1285 and the description is "out of memory". If I use `cube.draw` or `cube2.draw` in both windows, the error code of GLError is 1281 and the description is "invalid value".

It's curious and I'm confused. Can you help me?

**Comment by rougier** [comment]
Can you run the example with the `-debug` flag ?

**Comment by SunYangtian** [comment]
Thanks, I have solved that. The `I` in two windows can't be the same variable.

**Comment by rougier** [comment]
Oh yes, you're right. They are GPU buffer and are not shared between the two windows by default.
