### ISSUE TITLE
Default blending behavior

### ISSUE THREAD

**Issue by yuyu2172** [glumpy/glumpy#136]
I wonder if there is a rationale behind enabling `GL_BLEND` by default.
I prefer to set these options by myself than letting glumpy do it implicitly.
I had a hard time debugging this feature when I was porting C++ code that did not set these parameters on.

https://github.com/glumpy/glumpy/blob/master/glumpy/app/__init__.py#L254

**Comment by rougier** [comment]
No, no strong rationale. I'm ok to remove it but this mean each demo needs to be tested to check if it needs blending or not.
