### ISSUE TITLE
vsync option implemented?

### ISSUE THREAD

**Issue by victor-shepardson** [glumpy/glumpy#145]
it seems that the --vsync option does not do anything. I can't find anywhere in the code it is extracted from the parsed options, and the backends appear hardcoded to set vsync to false.

I'm able to turn vsync on manually, using GLFW for example: `glumpy.app.__backend__.glfw.glfwSwapInterval(1)` after window creation.

Would the proper way be to add a `vsync` keyword argument to each backend's `Window.__init__`, and pass `options.vsync` to it from the abstract `Window.__new__` in `app/__init__.py`?

Happy to make a PR, wanted to check if there is some reason it isn't done this way.

**Comment by rougier** [comment]
I think one if the reason is that not all backends support the vsync switch and I may have left the option without writing actual code. I would gladly accept a PR for that if you're willing to write it.

Also, the corresponding documentation should be updated accordingly.
