### ISSUE TITLE
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined

### ISSUE THREAD

**Issue by liyi14** [glumpy/glumpy#152]
Thanks for your effort!

I upgraded my system from Ubuntu 14.04 to Ubuntu 16.04 and upgraded the CUDA from 8.0 to 9.0 days before. Then I found the code which can work well before have some problems now. 

It reports 

> QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined

all the time and although I set the window invisible via

> self.window = app.Window(width=width, height=height, visible=False)

there is still a window showing the image I rendered.

Do you have any ideas what happened and what may cause this problem?

The same code can works well on another machine with Ubuntu 16.04 and CUDA 9.0, which makes me really puzzled what is the reason.

Would you be kind enough to give me some suggestions?

Thank you!

**Comment by rougier** [comment]
Might be related to [this](https://forum.qt.io/topic/26165/qopenglcontext-swapbuffers-called-with-non-exposed-window-behavior-is-undefined). It seems it is necessary to first test if the window is exposed before doing the swap.

**Comment by liyi14** [comment]
Oh, I solved it by installing libglfw. Thanks anyway!
