### ISSUE TITLE
glumpy.ext import Freetype library not found

### ISSUE THREAD

**Issue by jeff5048** [glumpy/glumpy#155]
Hi,
I am new to Python programming.  I am trying to work through this online book:
http://www.labri.fr/perso/nrougier/python-opengl/
I have installed the libraries it recommends.  
Python 3.6.0
Numpy 1.12.0
Scipy 0.18.1
Cython 0.25.2
Triangle 20170106
Glumpy 1.0.6

My Versions:
Python 3.6.5
numpy (1.14.5)
scipy (1.1.0)
Cython (0.28.3)
triangle (20170429)
glumpy (1.0.6)

I am getting a lot of errors from the glumpy library.  It started with freeType.  An example error:

File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\glumpy\ext\freetype\__init__.py", line 49, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found

The code was breaking on any call to the line:
from glumpy.ext import freetype

The strategy to fix is to pip install the freeType library and replace that line with
import freetype

This was done in several glumpy files making the call.  Then the errors started with the glfw library. An example error:

  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\glumpy\ext\glfw.py", line 60, in <module>
    raise OSError('GLFW library not found')
OSError: GLFW library not found

The glfw library was pip installed then the import glfw was inserted at the top of a file.  The current error:

File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\glumpy\app\window\backends\backend_glfw.py", line 89, in <module>
    __mouse_map__ = { glfw.GLFW_MOUSE_BUTTON_LEFT:   window.mouse.LEFT,
AttributeError: module 'glfw' has no attribute 'GLFW_MOUSE_BUTTON_LEFT'

The modified code in backend_glfw.py:

import glfw
…
try:
    #from glumpy.ext import glfw
    #__availability__ = True
    #__version__ = ("%d.%d.%d") % glfw.version
    __version__ = "1.6.0"
    #__init__()

    __mouse_map__ = { glfw.GLFW_MOUSE_BUTTON_LEFT:   window.mouse.LEFT,
                      glfw.GLFW_MOUSE_BUTTON_MIDDLE: window.mouse.MIDDLE,
                      glfw.GLFW_MOUSE_BUTTON_RIGHT:  window.mouse.RIGHT }

I just don’t know enough about Python to fix this.  And I suspect that every library glumpy calls using glumpy.ext import will have to be likewise rewritten.  There has got to be a better way, if so please educate me.  

System:
Windows 10 Pro
64 bit OS and processor
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32

Thanks,
Jeff

**Comment by jeff5048** [comment]
Update:  I found that by placing a period before the "gumpy." in the code "from glumpy.XXXX import" to make it look like "from .glumpy.XXXX import" resolved many of the issues.  The use of which seemed inconsistent because some code errored-out with the period.  This has something to do with revative vs. absolute file references in Python 3.6.  But there are other issues, too late in the day to get into now.

**Comment by rougier** [comment]
Thanks for the report. I may have forgot to explain that you have to install the freetype and GLFW libraries before installing corresponding Python packages.

**Comment by jeff5048** [comment]
I think the above issue has been resolved by the ".glumpy.XXXX import" method as now I am getting openGL errors.
