### ISSUE TITLE
Write some documentation on unclear points

### ISSUE THREAD

**Issue by Lecrapouille** [glumpy/glumpy#167]
Hi ! First, thanks for this lib, which seems to me the best OpenGL wrapper I could see so far (unfortunately not written in C++ what I needed) : even others C++ lib do not allow write minimalist OpenGL code as your lib can offer. I'm currently trying to make a simple portage of GLumpy into C++. Because I'm not a python and OpenGL programmer there is two points I did not found answers either in your documentation or inside the code. So maybe this issue can help improving the documentation.

1. Once you have create your VertexBuffer and its has been transfered from CPU to GPU, is it possible for GLumpy to do operations like resizing the VBO by appending/concatenating arrays with new data ? For example adding more vertices in the scene (ie. make a rasterization from CPU without using geometry shader) ? It seems to me that the answer is no (mainly because OpenGL poorly manages resizing VBOs). But is there a GLumpy trick to achieve this ? It seems to me that calling glBufferData with the currently used handle and a different size, OpenGL will realloc the VBO (but I cannot find back this information, so not sure of what I'm saying). So that means forcing `_need_create` with a new set of data so maybe calling the `delete` method without its  ̀_delete`?.

So, if I want to create an application which manages a dynamic number of vertices (for example a mesh editor) that means I cannot use VBO but I should use GLCollection. Am I right ?

2. VertexArray are not explicitly created (like in your 'easy way' tutorial). But since OpenGL 3.3 we need at least binding one VAO. Where/When GLumpy creates one ? In gloo-two-vertex-arrays.py you are using `.view(gloo.VertexArray)` so ok for me but how is it managed like done in your tutorial ?

Best regards

**Comment by Lecrapouille** [comment]
Thank you for your answer. I knew geogram but I never noticed their GLUP namespace. The code is well commented :)

For 2. I knew these files but what I did not understand well is the `self._buffer = self.view(VertexBuffer)` for VAO. If I understood well: VAO creates an empty VBO. Program when compiling creates a set of Attributes. Attributes use VAO when we call bind() method of Program (called by the constructor). After this, when Attribute is updated, the linked VAO is also updated and therefore activated. Am i right ?

**Comment by rougier** [comment]
Yes, I need to write this part of the documentation.
