### ISSUE TITLE
How do I set the rendered pixel values with other attributes instead of rgb?

### ISSUE THREAD

**Issue by wangg12** [glumpy/glumpy#172]
Hi, I've learned from the [colored cube example](https://glumpy.readthedocs.io/en/latest/tutorial/cube-nice.html). 

I was wondering how could I replace the color with other attributes, such as any floating-point data with 3 channels(including negative data) and render those attributes to the image plane? The expected result is a 3-channel array where the pixel values are the corresponding vertex attributes in the 3D model. 

However, it seems I can not directly replace the 'color' with other attributes. I am not sure how the attributes are conveted in the backend. Does anyone know how could this be done in glumpy? @rougier

**Comment by rougier** [comment]
I'm not sure to understand what you want to achieve. Do you have an example somewhere or a minimal code ? In the colored cube example, you can use any other attributes to set the color if you want.

**Comment by wangg12** [comment]
@rougier The negative values seems to be clamped to zeros.

**Comment by rougier** [comment]
You're right. But you can normalize your value before uploading and "unormalize" in the shader. But in any case, if you want to use the value as color, it has to be between 0 and 1.

**Comment by wangg12** [comment]
@rougier Got it. Thanks.
