### ISSUE TITLE
`gl.glDeleteFramebuffer` does not exist

### ISSUE THREAD

**Issue by tbung** [glumpy/glumpy#184]
`FrameBuffer._delete` calls `gl.glDeleteFramebuffer`, however this method does not exist. The correct method would probably be `gl.glDeleteFramebuffers` with a slightly different call signature.

If you are interested I can create a PR with the fix, I have already implemented it for my own usage.

Cheers,
Till

**Comment by rougier** [comment]
Thanks. A PR would be great!
