### ISSUE TITLE
Error in pvm_projection.py

### ISSUE THREAD

**Issue by sebftw** [glumpy/glumpy#185]
I noticed something odd when looking at
https://github.com/glumpy/glumpy/blob/master/glumpy/transforms/pvm_projection.py

It seems, on line 93, that it should have been
```self._zfar     = Transform._get_kwarg("zfar", kwargs) or 100.0```
When it is
```self._zfar     = Transform._get_kwarg("znear", kwargs) or 100.0```

**Comment by rougier** [comment]
You're right. Also, I think the `zfar` property is also wrong. Could you make  a PR?

**Comment by sebftw** [comment]
I will try. What do you mean that `zfar` is also wrong?

**Comment by rougier** [comment]
[Line 163](https://github.com/glumpy/glumpy/blob/606dae36e0f9e34fe183a138b6179b7ff2ad2079/glumpy/transforms/pvm_projection.py#L163), it returns `_znear` instead of `_zfar`

**Comment by sebftw** [comment]
Ahh I see. I have made the pull request:
https://github.com/glumpy/glumpy/pull/187
