### ISSUE TITLE
float indexing

### ISSUE THREAD

**Issue by jiangwei221** [glumpy/glumpy#201]
Hi:
When I run the example, matplotlib-3.py, I got following error:

File "///miniconda3/lib/python3.6/site-packages/glumpy/graphics/collections/base_collection.py", line 517, in _update
    texture = texture.reshape(shape[0],shape[1],4)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by jiangwei221** [comment]
The repo fixed it, but pip is not updated

**Comment by rougier** [comment]
Thanks for the report. This means a new release is necessary. Can you post an issue for that?

**Comment by jiangwei221** [comment]
sure
