### ISSUE TITLE
Unwanted transparency through the window

### ISSUE THREAD

**Issue by mdietrich16** [glumpy/glumpy#222]
When I'm using fonts or certain other objects (I have not tried that many), I can see the desktop or underlying programs through the application window where the characters or objects are placed.
For example with the 'font-agg.py' example, the outer pixels of each character exhibit this transparency, which makes the smaller fonts look like they are completely transparent.

Also, as a side note, running programs more than once with fonts does not display the font again, you have to restart the kernel to get it working again.

**Comment by rougier** [comment]
Can you post a screenshot of the problem and a minimal script ?

**Comment by mdietrich16** [comment]
If I can get glumpy to install :)

**Comment by rougier** [comment]
Maybe the clear color of the window has an alpha component that make it transparent. Can you play with that parameter ?

**Comment by mdietrich16** [comment]
I actually can't reproduce it anymore, sorry. I would reopen if I can find it again, but I do not find this behaviour anymore.
