### ISSUE TITLE
on_draw is called without the real need to redraw

### ISSUE THREAD

**Issue by zokrezyl** [glumpy/glumpy#223]
Hi,

I just bumped into the lovely examples/gloo-terminal.py and trying to combine with libvterm and make the terminal of the future :)

Well I noticed that on_draw is called several time per second, without the real need. I looked also into the app-simple.py and the behavior is the same.

Is this a bug, intended behavior or is it possible to control the refresh?

**Comment by zokrezyl** [comment]
Problem solved. I was not aware that it is possible to control the loop. Found an example for that. (examples/app-event-loop.py)

**Comment by rougier** [comment]
Yes, by default, framerate is 60 fps but you can also disable it by setting a framerate of 0.
