### ISSUE TITLE
Text dimming outside the center of the image

### ISSUE THREAD

**Issue by ivansiiito** [glumpy/glumpy#224]
Hi!

I'm trying to do a 3D representation of some data, as a set of points (with a text attached) on a sphere. It is very, very similar to the earth.py example. However, I don't understand why the marker and the text dims when outside the center of the image. I attach an image to show what I mean. In that image, you can see how Washington or Bishkent are barely visible.

I have looked for some information to avoid this effect during the last days, but I could not fix it yet. Could you help me with this?

Thanks a lot! 

![image](https://user-images.githubusercontent.com/5009070/62722384-f8ef7400-ba16-11e9-9a59-a019d777b82e.png)

**Comment by rougier** [comment]
In the shader code, you have two lines:
```
    v_fg_color.a = scale;
    v_bg_color.a = scale;
```

that control the alpha channel depending on the scale. If you comment out these two lines, the fading effect should dissapear.

**Comment by ivansiiito** [comment]
I fact it did.

Thanks a lot. That was exactly what I wanted to do.
