### ISSUE TITLE
Open fullscreen window on 2nd screen

### ISSUE THREAD

**Issue by thladnik** [glumpy/glumpy#225]
Hi, 

I want to use glumpy to display a fullscreen window on a 2nd screen while using the pyglet backend. 

In pyglet directly it works without any issues
```
import pyglet
from pyglet import app

display = pyglet.window.get_platform().get_default_display()
screens = display.get_screens()

window = pyglet.window.Window()
window.set_fullscreen(True, screen=screens[1])

app.run()
```

But in glumpy the method app.Window.set_fullscreen does not accept a screen parameter and I haven't found a way of accessing the underlying pyglet.window.Window instance for a direct call of set_fullscreen.

Has anyone maybe had this issue before and can tell me how to do it?

**Comment by rougier** [comment]
Hum, I never tried that but I think it might be possible. One start would be to look at the [glumpy pyglet backend](https://github.com/glumpy/glumpy/blob/master/glumpy/app/window/backends/backend_pyglet.py). Also, if you get the underlying pyglet window from glumpy, you might be able to use the pyglet code to set the second screen fullscreen.

**Comment by thladnik** [comment]
Thanks for the quick reply! I have created a pull request which implements this for the pyglet backend.
