### ISSUE TITLE
sdl2 backend doesn't work with the window's visible flag set to false

### ISSUE THREAD

**Issue by chalmersgit** [glumpy/glumpy#229]
In backend_sdl2.py, line 216

This:
flags |= SDL_WINDOW_HIDDEN

Should be:
flags |= sdl2.SDL_WINDOW_HIDDEN

I found this when I try to set the visible flag to false when creating a window.

**Comment by rougier** [comment]
Oh thanks for the report. Can you make a PR ?

**Comment by chalmersgit** [comment]
Done.
