### ISSUE TITLE
some links in the index.html are broken

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [glumpy/glumpy#235]
![image](https://user-images.githubusercontent.com/19762154/70393567-ad81bc80-1a2e-11ea-81c7-0e8278dd27d2.png)

I'm here from [your article](https://www.labri.fr/perso/nrougier/from-python-to-numpy)(it's really fun fun fun!) and this is some trivial issue though, I thought it's good to notify it.

**Comment by rougier** [comment]
Oh thanks. Can you make a PR?

**Comment by 0xF4D3C0D3** [comment]
> Oh thanks. Can you make a PR?

I'll close this issue and make a PR to your another [repo](https://github.com/glumpy/glumpy.github.io)

**Comment by rougier** [comment]
Thanks
