### ISSUE TITLE
raise RuntimeError('Freetype library not found') RuntimeError: Freetype library not found

### ISSUE THREAD

**Issue by Utkarsh22Ahuja** [glumpy/glumpy#249]
Hi everyone, please fix this error. 
I just imported glumpy and I receive this error. 
I am not able to work with this. RuntimeError: Freetype library not found. Please Help

Also the step by step instruction for installation given by you on https://glumpy.readthedocs.io/en/latest/ is not helping. Another doubt, I don't understand what is python3 folder? Where am I supposed to copy those dlls? And the statement either of the dlls, I am implying for win64 since my system is on win64. What exactly are you guys targetting?

My current version is 1.1.0 and it is not upgrading ('''pip install --upgrade glumpy''') <-- This is not working. 

I am a newbie in this field, Don't know much. Please help.

**Comment by rougier** [comment]
You might be missing the actual freetype library. Can you try installing freetype-py (that will install the DLL) to see if it fixed things ?

**Comment by Utkarsh22Ahuja** [comment]
With reference to my first comment in this issue, i already had freetype-py. I removed it, Installed it again just following your guidance. Eventually the same error pops up

**Comment by Frekby** [comment]
> 
> 
> With reference to my first comment in this issue, i already had freetype-py. I removed it, Installed it again just following your guidance. Eventually the same error pops up

what is your operating system?

**Comment by Utkarsh22Ahuja** [comment]
Windows 10 home(latest update). And I am using 64-bit operating system.

**Comment by Frekby** [comment]
> 
> 
> Windows 10 home(latest update). And I am using 64-bit operating system.
Try putting the file freetype.dll here Lib\site-packages\numpy\ext\freetype

**Comment by Frekby** [comment]
> 
> 
> Windows 10 home(latest update). And I am using 64-bit operating system.

Or in System32

**Comment by Utkarsh22Ahuja** [comment]
> > Windows 10 home(latest update). And I am using 64-bit operating system.
> 
> Try putting the file freetype.dll here Lib\site-packages\numpy\ext\freetype

Didn't Work



> > Windows 10 home(latest update). And I am using 64-bit operating system.
> 
> Or in System32

Did work but now I am receiving other error as 

'''Python38\site-packages\glumpy\app\clock.py", line 164, in <module>
    _default_time_function = time.clock
AttributeError: module 'time' has no attribute 'clock''''

Which is this line ---> '''_default_time_function = time.clock'''  in clock.py

**Comment by Frekby** [comment]
> 
> 
> > > Windows 10 home(latest update). And I am using 64-bit operating system.
> > 
> > 
> > Try putting the file freetype.dll here Lib\site-packages\numpy\ext\freetype
> 
> Didn't Work
> 
> > > Windows 10 home(latest update). And I am using 64-bit operating system.
> > 
> > 
> > Or in System32
> 
> Did work but now I am receiving other error as
> 
> '''Python38\site-packages\glumpy\app\clock.py", line 164, in
> _default_time_function = time.clock
> AttributeError: module 'time' has no attribute 'clock''''
> 
> Which is this line ---> '''_default_time_function = time.clock''' in clock.py

what version of python do you have

**Comment by Utkarsh22Ahuja** [comment]
I am using Python 3.8.2.

**Comment by Frekby** [comment]
> 
> 
> I am using Python 3.8.2.

maybe it's because of this, try version 3.6

**Comment by Utkarsh22Ahuja** [comment]
I have systems now working on latest version. I cannot degrade my version. Although I'll wait for you guys to update.

**Comment by Frekby** [comment]
> 
> 
> I have systems now working on latest version. I cannot degrade my version. Although I'll wait for you guys to update.

Try replacing time.clock with time.perf_counter

**Comment by rougier** [comment]
@Frekby you're right, the clock function has been deprecated and removed.

**Comment by Utkarsh22Ahuja** [comment]
Hi, it worked.
