### ISSUE TITLE
Unable to install glumpy on Ubuntu 14.04 : GLFW Library not found

### ISSUE THREAD

**Issue by aman-ks** [glumpy/glumpy#25]
Here's the traceback when I executed the commands for installation. 

    ./app-simple.py 
    Traceback (most recent call last):
      File "./app-simple.py", line 7, in <module>
    from glumpy import app
      File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.3-py2.7-linux-    x86_64.egg/glumpy/__init__.py", line 8, in <module>
        from . import app
      File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.3-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 17, in <module>
        from glumpy.ext.inputhook import inputhook_manager, stdin_ready
      File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.3-py2.7-linux-x86_64.egg/glumpy/ext/__init__.py", line 6, in <module>
        from . import glfw
      File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.3-py2.7-linux-x86_64.egg/glumpy/ext/glfw.py", line 60, in <module>
        raise OSError('GLFW library not found')
    OSError: GLFW library not found

I have already compiled and executed 'make' and 'make install' for GLFW 3.1.  Cannot understand why this is not working.

**Comment by rougier** [comment]
Do you know where is your glfw C library installed ?

**Comment by aman-ks** [comment]
It is in /usr/local/include

**Comment by aman-ks** [comment]
Also, I found this link https://stackoverflow.com/questions/25151085/unable-to-locate-package-glfw-on-linux-mint.  GLFW 3 won't work in 14.04, is it so? Should I try to get GLFW 2 working then ?

**Comment by rougier** [comment]
You need to install GLFW 3 from sources (and uninstall glfw library 2 first)

**Comment by aman-ks** [comment]
I purged all files related to glfw2 and then installed glfw3 using git.

(https://github.com/shurcooL/reusable-commands/blob/ed33ae496f36aaea735a1d183f77e833c92a9f3d/go-gl_glfw3_install.sh#L19-L32)

**Comment by aman-ks** [comment]
This worked.

**Comment by rougier** [comment]
Cool !

**Comment by ssinfod** [comment]
I have the same problem on Ubuntu 14.04. 
How do you remove (purge) glfw 2.7.2 from Ubuntu 14.04 ? 

Thanks
ssinfod

**Comment by rougier** [comment]
From the package manager, you should be able to uninstall it.

**Comment by ssinfod** [comment]
I found it, I had to use:
sudo apt-get purge libglfw-dev

**Comment by rougier** [comment]
Then follow the procedure above (to install glfw3) and glumpy should work hopefully.
