### ISSUE TITLE
how to properly assign uniform arrays?

### ISSUE THREAD

**Issue by lyssdod** [glumpy/glumpy#258]
Hi, I'm having a hard time understanding how to bind to uniform arrays in the shader. In the shader I have:

```glsl
uniform vec2 parts[128];
```

and then in the Python part:

```python
quad = gloo.Program(get_file('vertex.glsl'), get_file('fragment.glsl'), count=4)

for i in range(0, 128):
    quad[f'parts[{i}]'] = [0, i]
```

it doesn't matter if I try to wrap it into `nd.array` or not, the error I'm getting is 

```
  File "test_glumpy.py", line 87, in <module>
    quad[f'parts[{i}]'] = [0, i]
  File "/lib/python3.8/site-packages/glumpy/gloo/program.py", line 357, in __setitem__
    raise IndexError("Unknown item (no corresponding hook, uniform or attribute)")
IndexError: Unknown item (no corresponding hook, uniform or attribute)
```

there's not much examples involving arrays, but I thought it was kind of preferred syntax?

**Comment by rougier** [comment]
The parser is supposed to parse uniform arrays and you should able to assign values.
Does `quad["parts[0]"]` give an error ? Else, you can have a look at the [polar-surface.py](https://github.com/glumpy/glumpy/blob/master/examples/polar-surface.py#L45) example

**Comment by lyssdod** [comment]
@rougier thanks. it turns out that problem perishes when I specify array size directly and comes back if I do it via constant. so, following will fail:

```glsl
#define MAX_PARTS 128

uniform vec2 parts[MAX_PARTS];
```

```python
for i in range(0, 128):
    quad[f"parts[{i}]"] = [0, i]
```

I suppose it's a bug?

**Comment by rougier** [comment]
More or less, I think it's one of the limit of the parser I wrote.

**Comment by lyssdod** [comment]
I see, I will try to stick to consts then. Thanks!
