### ISSUE TITLE
Using collections to draw 3D objects

### ISSUE THREAD

**Issue by HukamiEstia** [glumpy/glumpy#261]
Hi, 
I am trying to render the results of a 3D object detector.

The output of the model is a set of 3D boxes rotated along the Z axis with different position inside a common coordinate system.
I tried to use a collection to render them but with no success.

How could I specify a different translation and rotation for each box? I tried to use transforms but I didn't find how to change them between each box and I tried to use uniforms but I couldn't pass a 4*4 matrix as uniform.

Thank you for your help

**Comment by rougier** [comment]
The trick is to use a texture to hold any uniform values you want. Have a look at the different collecion examples in the glumpy repository. Else, you can also have a regular vertex buffer  with each matrix being an attribute of a vertex if you do not have too many cubes.

**Comment by HukamiEstia** [comment]
That's what I had understood from the doc and collection example but I'm not familiar enough with the way opengl works and texture to make it work on my own. For now I went back to using a loop inside my on_draw...

What I tried was to add a mat4 to the gtype list and pass my rotation and translation matrices with an undefined scope ("!") So that they were added to the uniform attribute of the collection but it didn't work.

Could you give me a little more details on how to achieve this, where do I provide textures in my collection ?

**Comment by rougier** [comment]
You do not have to provide a texutre, it is created automtically by the collection depending on the type of base_dtype. "local" mean each vertex may have different value, "shared" means a group of vertex will share the value and "global" means every vertices will have the same value. In your case, for a cube, you want the position of each vertices to be local, the rotation matrix to be shared and the color to b either shared or global. Best is to start from the raw triangle collection and check how it is made.

**Comment by HukamiEstia** [comment]
Thanks, I looked into the raw triangle collection but I still don't understand how to pass a matrix as a shared uniform. 
Here is how I defined my dtype:
```
base_dtype = [('position',      (np.float32, 3), "!local", (0,0,0)),
                      ('b_rotation',    (np.float32, (4,4)), "shared",  np.eye(4, dtype=np.float32)),
                      ('b_translation', (np.float32, (4,4)), "shared",  np.eye(4, dtype=np.float32))]
```

then I create my rotation and translation matrices and append them together with my box's vertices to my collection:
```
rotation = glm.zrotate(np.eye(4, dtype=np.float32), angle)
translation = glm.translation(x, y, z)
boxes.append(bbox_coords, I, b_rotation=rotation, b_translation=translation)
```

but first I got a key error because of the gtype so I tried to add one for matrices but now I get a shader compilation error
which repeat those two messages:
```Error in Vertex shader 2 (<string>)
 -> error C7623: implicit narrowing of type from "vec4" to "float"

 ...
 042     _uniform = texture2D(uniforms, vec2(float(i++)/size_x,ty));
 043     b_rotation.xyzw = _uniform.xyzw;
 044 
 045     _uniform = texture2D(uniforms, vec2(float(i++)/size_x,ty));
 046     b_rotation.xyzw = _uniform.xyzw;
 ...

Error in Vertex shader 2 (<string>)
 -> error C1048: invalid character 'x' in swizzle "xyzw"

 ...
 045     _uniform = texture2D(uniforms, vec2(float(i++)/size_x,ty));
 046     b_rotation.xyzw = _uniform.xyzw;
 047 
 048     _uniform = texture2D(uniforms, vec2(float(i++)/size_x,ty));
 049     b_rotation.xyzw = _uniform.xyzw;
 ...
```

**Comment by rougier** [comment]
I think with current version, you can only pass flat vectors of 1,2,3 or 4 components. You can test with the `util.py` in collections. This script is responsible for generating the GLSL code that will create the uniforms from the texture (this called in the shader with the `fetch_uniforms()`).

**Comment by HukamiEstia** [comment]
Ok thank you, I will look into it. Could you point me some resources about textures that could help me understand how you use them as uniform?

**Comment by rougier** [comment]
I don't think there are any resources on this specific subject. The idea behind uniform as texture is to have the different values in the texture and to take care of reading it properly. This is one limitation of GL ES 2.0. Probably you can do much better with mode advanced GL API.

**Comment by HukamiEstia** [comment]
Ok thanks, I'm closing the issue.
