### ISSUE TITLE
examples issue

### ISSUE THREAD

**Issue by darewolf007** [glumpy/glumpy#263]
when i run the examples always get 
AttributeError: /usr/lib/x86_64-linux-gnu/libglfw.so.3.1: undefined symbol: glfwSetWindowMonitor
anybody help?

**Comment by rougier** [comment]
Sory for the delay. You finally fixed your problem?

**Comment by darewolf007** [comment]
oh! the problem has been done , but i still do not know the reason , may be i install it on anaconda virtual environment .
