### ISSUE TITLE
Beginner's question, using `arrow_stealth` to make quiver plots

### ISSUE THREAD

**Issue by lsmenicucci** [glumpy/glumpy#265]
Hi! I've posted this question on glumpy's gitter but since it appears to have no considerable activity, I'm also posting here.

I'm leaning the basics of OpenGL for making animated quiver plots and I can't understand very well the vertex and fragment shaders of this [example](https://www.labri.fr/perso/nrougier/python-opengl/#id37). In that example only 4 vertexes can create a bunch of arrows using `arrow_stealth`, I can't understand how that's possible. Furthermore, wouldn't be necessary at least 4N floats for drawing N 2D arrows individually?

**Comment by rougier** [comment]
I disabled gitter notation. I need to put them back.

To asnwer your question, the quiver examples works by drawing each arrow at the pixel level in the fragment shader. If you've read the book, you'll see we can creates SDF shapes using some distance functions. In the quiver example, it's exactly the same but I used some parametrization to have a bunch of arrows.

**Comment by lsmenicucci** [comment]
Thanks for the reply @rougier! [SDFs ](https://en.wikipedia.org/wiki/Signed_distance_function) guided me on how fragment shaders are commonly implemented. Can't really cut corners 😅 Here's my result:

![image](https://user-images.githubusercontent.com/4942894/96023914-7be53900-0e29-11eb-95e2-21f1832bcedb.png)

Thanks for the attention!

**Comment by rougier** [comment]
Nice !
