### ISSUE TITLE
float cannot be converted to int error in sdf_font.py

### ISSUE THREAD

**Issue by qiujiangkun** [glumpy/glumpy#268]
I'm running this code with latest numpy
```python
from glumpy.graphics.text import FontManager
regular = FontManager.get("SourceCodePro-Regular.otf")
```
But this happened:
`float cannot be converted to int`
I can fix it by modifying line 45 and 46 of sdf_font.py
```python
int(ratio * nrows)
int(ratio * ncols)
```

**Comment by rougier** [comment]
Oh great, thanks for the report. Can you make a PR?

**Comment by jstreibel** [comment]
Shouldn't this be marked as closed?
