### ISSUE TITLE
Multiple windows resizing problems

### ISSUE THREAD

**Issue by CarlosBergillos** [glumpy/glumpy#277]
When using multiple app windows, the context is kept at the last window added, and this causes erroneous behaviour when resizing the other windows (resizing the window as in regular resizing via the mouse on the corner).

Minimum working example (when resizing the first window, it's the second one that changes its buffer size, erroneously):
```python
from glumpy import app, gloo, gl

app.use('glfw')
window1 = app.Window(color=(0,0,0,1))
window2 = app.Window(color=(1,1,1,1))

vertex = """
attribute vec2 position;
void main (void) {
    gl_Position = vec4(0.85*position, 0.0, 1.0);
}
"""

fragment = """
void main(void) {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
"""

@window1.event
def on_draw(dt):
    window1.clear()
    quad1.draw(gl.GL_TRIANGLE_STRIP)

@window2.event
def on_draw(dt):
    window2.clear()
    quad2.draw(gl.GL_TRIANGLE_STRIP)

quad1 = gloo.Program(vertex, fragment, count=4)
quad1['position'] = [(-1,-1), (-1,+1), (+1,-1), (+1,+1)]

quad2 = gloo.Program(vertex, fragment, count=4)
quad2['position'] = [(-1,-1), (-1,+1), (+1,-1), (+1,+1)]

app.run()
```

Adding the line `self.activate()` to `on_resize` in 'app/window/window.py' seems to fix it.

```python
    def on_resize(self, width, height):
        """" Default resize handler that set viewport """
        self.activate() ## new line
        gl.glViewport(0, 0, width, height)
        self.dispatch_event('on_draw', 0.0)
        self.swap()
```

I've only tested with 'glfw' backend, since it's the only one I have installed. I presume this might / might not be a problem on other backends that support multiple windows depending on if/how they've overwritten the on_resize methods (I haven't checked).

If the above fix is reasonable, I can submit a PR. I'm not too familiar with backends and this library, so I first wanted to make sure.
And maybe it's better to make this fix by overriding `on_resize` in `backend_glfw.py`? in case some other backends don't implement `.activate()`. (or add the line to `on_framebuffer_resize` in `backend_glfw.py` , I'm not sure about the difference)

**Comment by rougier** [comment]
Many thanks for the report and the fix! A PR would be most welcomed yes and it can be easily adapted ot other backends. The `on_framebuffer_resize` might need different treatment, this is mostly used for off-screen rendering (look ad the blur demo for example). But I remember there are other problmes with framebuffer where it is not resized properly. For your PR, best is to stick to live window adn then we can check if this is also required for framebuffers.
