### ISSUE TITLE
Problems with Texture2D

### ISSUE THREAD

**Issue by brorfred** [glumpy/glumpy#28]
Hi!

Trying to install glumpy and try it on a Mac Pro with Yosemite and macports. I have two, probably related issues. When I import glumpy, I get the following warning:

In [2]: import glumpy
[w] Cannot set error on copy on GPU copy

Then when I run any of the more complex examples, I get the following errors:

run voronoi.py
[i] Using GLFW (GL 2.1)
[i] Running at 60 frames/second
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/bror/git/code/glumpy/examples/voronoi.py in <module>()
    109 cones.bind(C)
    110 
--> 111 app.run()

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/__init__.pyc in run(clock, framerate, interactive, duration, framecount)
    299     global __running__
    300 
--> 301     clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
    302     options = parser.get_options()
    303 

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/__init__.pyc in __init__(clock, framerate, backend)
    259 
    260         # Dispatch an initial resize event
--> 261         window.dispatch_event('on_resize', window._width, window._height)
    262 
    263     return __clock__

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
    377             except TypeError:
    378                 self._raise_dispatch_exception(
--> 379                     event_type, args, getattr(self, event_type))
    380 
    381         if invoked:

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
    373             try:
    374                 invoked = True
--> 375                 if getattr(self, event_type)(*args):
    376                     return EVENT_HANDLED
    377             except TypeError:

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/window/window.pyc in on_resize(self, width, height)
    191         """" Default resize handler that set viewport """
    192         gl.glViewport(0, 0, width, height)
--> 193         self.dispatch_event('on_draw', 0.0)
    194         self.swap()
    195 

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
    366                         return EVENT_HANDLED
    367                 except TypeError:
--> 368                     self._raise_dispatch_exception(event_type, args, handler)
    369 
    370 

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
    363                 try:
    364                     invoked = True
--> 365                     if handler(*args):
    366                         return EVENT_HANDLED
    367                 except TypeError:

/Users/bror/git/code/glumpy/examples/voronoi.py in on_draw(dt)
     59 @window.event
     60 def on_draw(dt):
---> 61     with borders:
     62         window.clear()
     63         gl.glEnable(gl.GL_DEPTH_TEST)

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/graphics/filter.pyc in __enter__(self)
    148         # Prepare framebuffer for "original" rendering
    149         gl.glViewport(0, 0, self.width, self.height)
--> 150         self._framebuffers[0].activate()
    151 
    152 

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/gloo/globject.pyc in activate(self)
     88             self._need_create = False
     89 
---> 90         self._activate()
     91 
     92         if self.need_setup:

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/gloo/framebuffer.pyc in _activate(self)
    378 
    379         if self._need_attach:
--> 380             self._attach()
    381             self._need_attach = False
    382         attachments = [gl.GL_COLOR_ATTACHMENT0+i for i in range(len(self.color))]

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/gloo/framebuffer.pyc in _attach(self)
    407                 buffer.deactivate()
    408             elif isinstance(buffer, Texture2D):
--> 409                 buffer.activate()
    410                 # INFO: 0 is for mipmap level 0 (default) of the texture
    411                 gl.glFramebufferTexture2D(gl.GL_FRAMEBUFFER, attachment,

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/gloo/globject.pyc in activate(self)
     95 
     96         if self.need_update:
---> 97             self._update()
     98             self._need_update = False
     99 

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/gloo/texture.pyc in _update(self)
    312             gl.glBindTexture(self._target, self.handle)
    313             gl.glTexSubImage2D(self.target, 0, x, y, width, height,
--> 314                                self._cpu_format, self.gtype, self)
    315             gl.glBindTexture(self._target, self.handle)
    316 

latebind.pyx in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)()

wrapper.pyx in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6294)()

wrapper.pyx in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:4241)()

wrapper.pyx in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3601)()

wrapper.pyx in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3520)()

/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/OpenGL/GL/images.pyc in __call__(self, arg, baseOperation, pyArgs)
    455         type = pyArgs[ self.typeIndex ]
    456         arrayType = arrays.GL_CONSTANT_TO_ARRAY_TYPE[ images.TYPE_TO_ARRAYTYPE[ type ] ]
--> 457         return arrayType.asArray( arg )
    458 #       def cResolver( self, array ):
    459 #               return array

arraydatatype.pyx in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)()

arraydatatype.pyx in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)()

TypeError: ("No array-type handler for type <class 'glumpy.gloo.texture.Texture2D'> (value: Texture2D([[[ 0.,  0.,  0.],\n        [ 0.,  0.,  0) registered", <OpenGL.GL.images.ImageInputConverter object at 0x10a5ba750>)

Any idea of what I'm doing wrong? I've tried using virtualenv to avoid problems from my normal setup.

/Bror

**Comment by rougier** [comment]
From this log, it seems to be related to the OpenGL_accelerate framework.
Can you try without (but with OpenGL) ?

What about other examples, do they work properly (tiger.py for example) ?
voronoi.py isusing the framebuffer, this might be also a problem with the framebuffer.

**Comment by brorfred** [comment]
Hm, not tiger.py generates a segfault:

In [16]: run tiger.py
[i] Requesting "tiger.svg" from remote server
[i] Fetching data (110724 bytes) to "/Users/bror/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/data/tiger.svg"
[w] Unhandled SVG tag (metadata)
[w] Unhandled SVG tag (defs)
[i] Using GLFW (GL 2.1)
Segmentation fault: 11


app.simple.py seems to work - only generates a black window though.

app-two-windows is weird:

In [6]: run app-two-windows.py
[w] Forward compatibility only exist for OpenGL version 3.0 and above
[x] Window creation failed

In [7]: run app-two-windows.py
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[w] The GLFW library is not initialized
[x] Window creation failed

This happens quite often as well when first importing glumpy:

In [2]: from glumpy import app
[w] Cannot set error on copy on GPU copy

In [3]: from glumpy import app

In [4]:

**Comment by rougier** [comment]
What do you get from the `glxinfo`command (first few lines only) ?

**Comment by brorfred** [comment]
[bror@:ruote ~]$ glxinfo
name of display: /private/tmp/com.apple.launchd.4l9gPRTVMp/org.macosforge.xquartz:0
Warning: GL error 0x500 at line 922
display: /private/tmp/com.apple.launchd.4l9gPRTVMp/org.macosforge.xquartz:0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_import_context, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_MESA_multithread_makecurrent, GLX_OML_swap_method, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig
OpenGL vendor string: ATI Technologies Inc.
OpenGL renderer string: AMD Radeon HD - FirePro D500 OpenGL Engine
OpenGL core profile version string: 2.1 ATI-1.30.5
OpenGL core profile shading language version string: 1.20
OpenGL core profile extensions:

OpenGL version string: 2.1 ATI-1.30.5
OpenGL shading language version string: 1.20
OpenGL extensions:
    GL_APPLE_aux_depth_stencil, GL_APPLE_client_storage, 
    GL_APPLE_element_array, GL_APPLE_fence, GL_APPLE_float_pixels, 
    GL_APPLE_flush_buffer_range, GL_APPLE_flush_render, 
    GL_APPLE_object_purgeable, GL_APPLE_packed_pixels, GL_APPLE_pixel_buffer, 
    GL_APPLE_rgb_422, GL_APPLE_row_bytes, GL_APPLE_specular_vector, 
    GL_APPLE_texture_range, GL_APPLE_transform_hint, 
    GL_APPLE_vertex_array_object, GL_APPLE_vertex_array_range, 
    GL_APPLE_vertex_point_size, GL_APPLE_vertex_program_evaluators, 
    GL_APPLE_ycbcr_422, GL_ARB_color_buffer_float, GL_ARB_depth_buffer_float, 
    GL_ARB_depth_clamp, GL_ARB_depth_texture, GL_ARB_draw_buffers, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_instanced, 
    GL_ARB_fragment_program, GL_ARB_fragment_program_shadow, 
    GL_ARB_fragment_shader, GL_ARB_framebuffer_object, 
    GL_ARB_framebuffer_sRGB, GL_ARB_half_float_pixel, 
    GL_ARB_half_float_vertex, GL_ARB_imaging, GL_ARB_instanced_arrays, 
    GL_ARB_multisample, GL_ARB_multitexture, GL_ARB_occlusion_query, 
    GL_ARB_pixel_buffer_object, GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_provoking_vertex, GL_ARB_seamless_cube_map, GL_ARB_shader_objects, 
    GL_ARB_shader_texture_lod, GL_ARB_shading_language_100, GL_ARB_shadow, 
    GL_ARB_shadow_ambient, GL_ARB_sync, GL_ARB_texture_border_clamp, 
    GL_ARB_texture_compression, GL_ARB_texture_compression_rgtc, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_float, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_transpose_matrix, 
    GL_ARB_vertex_array_bgra, GL_ARB_vertex_blend,

**Comment by rougier** [comment]
I get pretty much the same bue the "Warning: GL error 0x500 at line 922".

**Comment by rougier** [comment]
I meant I do not get the "Warning: GL error 0x500 at line 922"
