### ISSUE TITLE
Installing from pypi on python 3.8+

### ISSUE THREAD

**Issue by merny93** [glumpy/glumpy#285]
The update to handle the depreciated function `time.clock` in python 3.8 which was pushed on feb 23, 2020 is not on pypi resulting in an unusable installation for python 3.8+ users.

The work around fix is simply to go into the app/clock.py and change line 164 which reads:
`_default_time_function = time.clock`
and switch it to:
`_default_time_function = time.perf_counter`

Hope this helps some people!

**Comment by rougier** [comment]
Thanks for the report. I've uploaded a new version at https://pypi.org/project/glumpy/1.2.0/

**Comment by merny93** [comment]
Sweet! Thanks for fixing it
