### ISSUE TITLE
Split out glumpy.gloo into a standalone library.

### ISSUE THREAD

**Issue by luisbc92** [glumpy/glumpy#289]
glumpy.gloo is a powerful module that could be useful on its own, along with a different library to create a context (such as glcontext). ModernGL aims to provide similar functionality but is missing some abstractions compared to gloo.

Browsing the code, it seems that gloo is already independent from the rest of glumpy. Would you have the time to create a separate project for gloo? Otherwise, I can do it and credit you.

**Comment by jstreibel** [comment]
I'm not entirely sure but I think it already is a module (almost) on its own: [gloo](https://vispy.org/getting_started/gloo.html)

I say almost bc it's a submodule of vispy.

And I say not entirely sure bc it might be lagging behind or discontinued outside Glumpy.

**Comment by rougier** [comment]
@jstreibel I agree. If I make a separate package, I would have to maintain the two and most probably one would lag behind other.

**Comment by luisbc92** [comment]
The reason I would like to have it on its own is to avoid including the dependencies the rest of **glumpy** or **vispy** need, namely **triangle** which forces me to depend on build tools as it is a C library.

However I just realized that **vispy** has no dependencies other than **numpy** so I might just use that!

Thanks.
