### ISSUE TITLE
Shader library support to GLSL version > 140

### ISSUE THREAD

**Issue by jstreibel** [glumpy/glumpy#293]
Shader library yields this error when compiling glsl version higher than 140:
```
Error in Fragment shader 5 (<string>)
 -> error C7616: global function texture1D is removed after version 140

 ...
 365 vec3 colormap_user(float t)
 366 {
 367     return texture1D(colormap, t).rgb;
 368 }
 370 vec3 colormap_user(float t, vec3 under, vec3 over)
 ...
```
WebGL 2.0 is based on OpenGL ES 3.0 which is based on GLSL 3.30.

I propose a change to texture function call in file `library/colormaps/user.glsl` (or any files necessary).

**Comment by rougier** [comment]
But then it'll fail with version <140, no?

**Comment by jstreibel** [comment]
Yes. And it gets a warning in ver 130.

If its the case of being ubiquitous, webgl2 should be everywhere now and it supports glsl 330.

How important is support to 120?

**Comment by jstreibel** [comment]
Added a workaround in PR #292
