### ISSUE TITLE
RuntimeError: Freetype library not found

### ISSUE THREAD

**Issue by Hammad-hab** [glumpy/glumpy#301]
Hi, I am trying to learn OpenGL in python by using glumpy and when try to run the folllowing code on MacOS:
```
from glumpy import app, gloo, gl


vertex = """
  uniform float scale;
  attribute vec2 position;
  attribute vec4 color;
  varying vec4 v_color;
  void main()
  {
    gl_Position = vec4(scale*position, 0.0, 1.0);
    v_color = color;
  } """

fragment = """
  varying vec4 v_color;
  void main()
  {
      gl_FragColor = v_color;
  } """
  
quad = gloo.Program(vertex, fragment, count=4)

quad['color'] = [ (1,0,0,1), (0,1,0,1), (0,0,1,1), (1,1,0,1) ]
quad['position'] = [ (-1,-1),   (-1,+1),   (+1,-1),   (+1,+1)   ]
quad['scale'] = 1.0

window = app.Window()
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)
app.run()
```

it keeps giving me `raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found`
I know that this error is a duplicate of https://github.com/glumpy/glumpy/issues/249 but it doesn't solve my problem because I can't find a freetype.dll for MacOS

**Comment by rougier** [comment]
Can you install freetype-py and check if it works?

**Comment by Hammad-hab** [comment]
I have already installed freetype-py via pip

**Comment by tovacinni** [comment]
You may also have to run `condo install freetype` on OSX

**Comment by rougier** [comment]
Does `import freetype` works?

**Comment by liruilong940607** [comment]
`brew install freetype` should work on MAC.
