### ISSUE TITLE
Issue with GLFW ImGui backend on WSL2

### ISSUE THREAD

**Issue by Leotinoooo** [glumpy/glumpy#304]
Hello,

Thanks for your cool library!
I ran into an issue while using `glumpy` through the `kaolin-wisp` repository NVIDIAGameWorks/kaolin-wisp#66. In this library, `glumpy` is used with the GLFW ImGui backend and I narrowed down the issue to WSL2 as you can see in the below notes.

### Setup

- I'm using WSL2 with Ubuntu 20.04 on my machine, with an RTX 3080 (Driver version 511.65, CUDA version 11.6).
- Python version is 3.8.10
- I created a virtual environment in which I installed `glumpy` from the repository (`pip install git+https://github.com/glumpy/glumpy.git@46a7635c08d3a200478397edbe0371a6c59cd9d7`), and other libraries to run the sample code. Here's the pip freeze of the virtual environment:
```
Cython==0.29.32
glfw==2.5.5
glumpy==1.1.1
imgui==1.4.1
numpy==1.23.4
PyOpenGL==3.1.6
PyOpenGL-accelerate==3.1.5
triangle==20220202
```

### Method

- I'm using VcxSrv as my X server to render windows.
- I confirmed that interactive windows could be rendered, using the `glxgears` demo from mesa-utils.
- I also confirmed that the GLFW backend works running the following sample code:
```
from glumpy import app
window = app.Window()
```

### Issue

I tried running the following sample code to use the GLFW ImGui backend (like in the `kaolin-wisp` repository).
```
from glumpy import app
app.use("glfw_imgui")
window = app.Window()
```
But it led to this issue:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/glumpy-1.1.1-py3.8-linux-x86_64.egg/glumpy/app/__init__.py", line 188, in __new__
    window = __backend__.Window(*args, **kwargs)
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/glumpy-1.1.1-py3.8-linux-x86_64.egg/glumpy/app/window/backends/backend_glfw_imgui.py", line 248, in __init__
    self.imguiRenderer = GlfwRenderer(self._native_window, attach_callbacks=False)
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/imgui/integrations/glfw.py", line 13, in __init__
    super(GlfwRenderer, self).__init__()
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/imgui/integrations/base.py", line 17, in __init__
    self._create_device_objects()
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
  File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/home/user0/test/glumpy_test/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        baseOperation = glGetUniformLocation,
        cArguments = (1, b'Texture\x00'),
        result = -1
)
```
If you have time to provide some help on this, it would be awesome!

**Comment by rougier** [comment]
The error on `glGetUniformLocation` does not look good because it's a standard GL method. It seems there's no GL ES context. Can you run glinfo and check what is said about GL?

**Comment by Leotinoooo** [comment]
Hello @rougier,

Thanks for your answer! 
Here's the output of `glxinfo -B`:
```
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA GeForce RTX 3080) (0xffffffff)
    Version: 21.2.6
    Accelerated: yes
    Video memory: 42807MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce RTX 3080)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by rougier** [comment]
Coudl you try to run https://www.labri.fr/perso/nrougier/python-opengl/code/chapter-03/glut-quad-solid.py (it comes from https://www.labri.fr/perso/nrougier/python-opengl/)?

**Comment by Leotinoooo** [comment]
@rougier,
I ran the script you provided in the same virtual environment, it resulted in the Hello World window with the red background, as expected I guess.

**Comment by rougier** [comment]
Thanks. I think there may be a problem at [line 248](https://github.com/glumpy/glumpy/blob/master/glumpy/app/window/backends/backend_glfw_imgui.py#L248) where glfw is trying to get the native window and because of your setup, it might get it wrong. To debug, you could start with the glfw and add extra lines from glfw_imgui incrementally to check which one break things. Or compare native windows from glumpy and using an external tool (I think there's a tool on X for that).

**Comment by Leotinoooo** [comment]
I've identified the possible issue, thanks to pyimgui/pyimgui#309. The issue might be [here](https://github.com/glumpy/glumpy/blob/master/glumpy/defaults.py#L175), where the default OpenGL versions are set to be between 1 and 2. By setting these two values to 3, I was able to open a window with the glfw_imgui backend. 

However, this is only a temporary workaround. I don't know how this change would be robust to other setups, or if this could be fixed in another way. What do you think?

**Comment by rougier** [comment]
You can choose your GL context actually, check [app-config.py](https://github.com/glumpy/glumpy/blob/master/examples/app-config.py)

**Comment by Leotinoooo** [comment]
@rougier,
Understood, this may be the most convenient solution. I will close the issue, merci !
