### ISSUE TITLE
Problems with text placements in material-colors example

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#31]
![image](https://cloud.githubusercontent.com/assets/1942359/6731942/e589e33c-ce48-11e4-8439-ce3248388cf7.png)

**Comment by rougier** [comment]
Does the text zoom when you zoom with mouse scroll ?

**Comment by rossant** [comment]
yes

**Comment by rougier** [comment]
Maybe a precision problem. What is the hardware ?

**Comment by rossant** [comment]
Same pb with intel hd graphics and nvidia

**Comment by rougier** [comment]
Weird. Can you try different `scale' in text (lines 49 & 52)

**Comment by rossant** [comment]
.02 instead of .002

![image](https://cloud.githubusercontent.com/assets/1942359/6735982/5281b5d2-ce62-11e4-9d52-28f820d72b6b.png)

**Comment by rougier** [comment]
Hum, not whole text scaled up.
