### ISSUE TITLE
How to update collection inside the shader ?

### ISSUE THREAD

**Issue by Lecrapouille** [glumpy/glumpy#322]
@rougier Hello, I'm stuck since there is no documentation concerning collections, so I made hypotheses from my reading of glumpy code source, but I just realized I made a wrong hypothesis: glumpy does not offer updating items from the vertex shader !!!

I am right if I say:
- that items of the collection are stored inside a texture.
- you can read their fields thanks the shader function `fetch_uniforms()`. This function copies the content of the current item into `varying` variables with the name of the field.
- **but, from the shader side, we cannot modify/update item directly in the texture** ? Texture are read-only, so no `save_uniforms()` function ?
- to update items you have to modify them from the CPU side, glumpy will refresh the texture.
- In my opinion, this sucks since we cannot do full shader simulations because we need to do CPU/GPU refresh transferring a whole texture each time.

Let suppose I want to make a galaxy simulation using a collection of stars (I'm not referring to your galaxy example).

- I create my new type stars extending points:
```
stars = PointCollection(
    user_dtype = [("mass",  (np.float32, 1), 'shared', 1),
                  ("speed", (np.float32, 3), 'shared', 1),
                  ("acceleration",   (np.float32, 3), 'shared', 1)],
    color = "shared", mode = "agg", vertex = my_vertex_shader, fragment = my_fragment_shader)
```

- at the init of my application, CPU side, I append new items (stars) in the collection. 

```
stars.append(position, size=1, mass=1, speed=[1,2,3], acceleration=[0,0,0])
```

How to write my vertex shader to do something like:
```
void main()
{
  fetch_uniforms();
  acceleration = ...;
  speed += step * acceleration;
  position += step * speed;
}
```

The only example I found i collection-update.py and positions are modified CPU side. How to deal shader only ?

**Comment by Lecrapouille** [comment]
Ok I made some investigations:
- this method has a name: "shader computer" but need OpenGL >= 4, so out of this scope.
- project like this one https://github.com/skanti/Gaussian-Filter-GPU-OpenGL stores data on the texture but for a FBO (not the screen) and in the fragment shader (not from the vertex shader). But I guess you cannot store on several pixels for storing floating point values. So I guess this is not OpenGL-ES possible

**Comment by rougier** [comment]
Sorry for delay. Glumpy is based on OpenGL ES 2.0 and it has a lot of limitations. The use of textures for collection was a hack I did to be able to have some cheap version of uniform buffers. The way to update the collection would then be to update the texture with the right content.

**Comment by Lecrapouille** [comment]
No worries about the delay. I guess this is not a limitation of GLumpy but a limitation of OpenGL since only its version 4.3 offers compute shaders (and of course Mac OS does not support this version of OpenGL). I initially thought collections were more OpenCL buffers than uniform buffers. When you said 'to update the texture with the right content' I found it sad because the interest is to achieve 100% computation inside shaders (with update) and avoid CPU <--> GPU transfers for updating states of the simulation. In addition glumpy could have offered the same behavior as OpenCL but in 2 lines of code instead of 1000 lines of OpenCL init.
