### ISSUE TITLE
WebGL backend

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#34]
How complicated it would be to implement a WebGL backend? Assuming we have a `gloo.js` that implements gloo in JavaScript, we'd at least need to export an entire window to a structure with the list of programs, GLSL, variables, data, etc.

Alternatively, we could have another gloo implementation which creates such structure instead of displaying something, or it could generate GLIR commands like in VisPy.

For interactivity we can always reimplement it in JavaScript on top of gloo.js.

**Comment by rougier** [comment]
Well my secret plan is to use the GLIR protocol such that no change is needed from the IPython side.
First step was to  check glumpy.gl can intercept every GL calls (https://github.com/glumpy/glumpy/blob/master/glumpy/gl.py) and then I would need to use GLIR instead.

By the way, what's the status of the GLIR chapter ?

Last option is to wait for Vulkan... From what I've understood, it's very like GLIR and SPIR might be the same thing.

**Comment by rossant** [comment]
> Well my secret plan is to use the GLIR protocol such that no change is needed from the IPython side.
> First step was to check glumpy.gl can intercept every GL calls (https://github.com/glumpy/glumpy/blob/master/glumpy/gl.py) and then I would need to use GLIR instead.

I don't know if it's enough to intercept the GL calls, because GLIR is at a slightly higher level (for example `SHADER` corresponds to many individual GL calls)

> By the way, what's the status of the GLIR chapter ?

It's done, I think the whole book will be published within the next few months.

> Last option is to wait for Vulkan... From what I've understood, it's very like GLIR and SPIR might be the same thing.

Yeah, I think Vulkan is very interesting. SPIR is indeed in the same spirit than GLIR, but at a much lower level. It's basically a LLVM IR for GPU, which makes it theoretically possible to write shaders in pure Python (using a Python-to-LLVM compiler like Numba). That could potentially make the whole parsing/GLSL code generation obsolete. Personally I'd very much prefer to write shaders in Python rather than using a Python API to generate GLSL strings on-the-fly...

With Vulkan you allocate memory on the GPU and it's your responsability to manage it. You can easily segfault the GPU if you don't do it right. Vulkan is especially meant to be used with multithreading but that's probably unnecessary for what we do (and there's the GIL problem anyway). Using Vulkan/SPIR for VisPy or Glumpy would probably require starting completely from scratch (at least the gloo implementation and the snippet stuff). But OpenGL will still be supported for years.

Also there is no word about Vulkan/SPIR in the browser at this point, and I'm not sure we'll have an alternative to WebGL in the foreseeable future (see https://redditjs.com/r/vulkan/comments/2zdwo9/L/cpinjnd). So if we want to support the browser, we probably need to stick to OpenGL for now. Things will probably be clearer by the end of the year.
