### ISSUE TITLE
Event handler stack

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#35]
In glumpy what are the use cases for `push_handlers` and `pop_handlers`?

**Comment by rougier** [comment]
I took the event system directly from pyglet. The use case is explained at http://www.pyglet.org/doc/programming_guide/stacking_event_handlers.html.

So roughly, you can write a class with events and push the class (push_handlers) such that event get all connected at once.

**Comment by rossant** [comment]
Do you use this somewhere in Glumpy?

**Comment by rougier** [comment]
I don't know, I have to check
