### ISSUE TITLE
api.matplotlib not imported with pip

### ISSUE THREAD

**Issue by brorfred** [glumpy/glumpy#37]
I tried to install glumpy via pip and virtualenvwrapper. All basic examples works, with the exception of matplotlib. Trying

from glumpy.api.matplotlib import *

Generates the error 

ImportError: No module named matplotlib

The folder  ~/.virtualenvs/glumpy/lib/python2.7/site-packages/glumpy/api/ is empty.

Installing via *git clone* and *python setup.py* install works fine.

 pip freeze
Cython==0.22
Pillow==2.7.0
PyOpenGL==3.1.0
glumpy==1.0.3
gnureadline==6.3.3
ipython==3.0.0
line-profiler==1.0
matplotlib==1.4.3
mock==1.0.1
nose==1.3.4
numpy==1.9.2
pyparsing==2.0.3
python-dateutil==2.4.1
pytz==2015.2
scipy==0.15.1
six==1.9.0
triangle==2013.04.05
wsgiref==0.1.2

**Comment by rougier** [comment]
Thanks. I think I have fixed the problem but not yet committed to pip.
One "glumpy.api.matplotlib" was missing from what I remember.
