### ISSUE TITLE
newer numpy versions

### ISSUE THREAD

**Issue by guidov** [glumpy/glumpy#42]
Hi,
I'm getting this error when running many of the examples.
Could this be due to me using a version of numpy?

TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'

**Comment by rougier** [comment]
Hu, strange. Can you post the full traceback (with the simplest example that has the bug) ?

**Comment by guidov** [comment]
Here is an example with svg-path.py

——> python svg-path.py
[i] Using GLFW (GL 4.4)
Traceback (most recent call last):
  File "svg-path.py", line 39, in <module>
    paths.append(vertices, closed=closed)
  File
"/usr/local/lib/python2.7/dist-packages/glumpy-1.0.3-py2.7-linux-x86_64.egg/glumpy/graphics/collections/agg_path_collection.py",
line 190, in append
    I += np.repeat( 4*np.arange(n), 6)
TypeError: Cannot cast ufunc add output from dtype('int64') to
dtype('uint32') with casting rule 'same_kind'


My numpy version is:
In [2]: from numpy.version import full_version

In [3]: full_version
Out[3]: '1.10.0.dev0+0752872'


On Mon, Jun 1, 2015 at 3:43 PM, Nicolas P. Rougier <notifications@github.com

**Comment by rougier** [comment]
My version is 1.9.2. Do you have a possibility to upgrade your version ?

**Comment by guidov** [comment]
I downgraded to numpy version 1.9.2 from the developmental branch that I
had "1.10.0.dev0+0752872" and reinstalled glumpy and the examples work now.




On Tue, Jun 2, 2015 at 1:13 AM, Nicolas P. Rougier <notifications@github.com

**Comment by rougier** [comment]
Oops, sorry, I did not realize you get the dev version...
