### ISSUE TITLE
Add screens into quickstart

### ISSUE THREAD

**Issue by techtonik** [glumpy/glumpy#43]
The [quickstart](http://glumpy.github.io/quickstart.html) is boring without screenshots. =)

**Comment by rougier** [comment]
I'm now working on documentation, this should be soon fixed.

**Comment by techtonik** [comment]
Nice.Let me know when it is finished.

**Comment by rougier** [comment]
@techtonik 
Not yet finished but in better shape: http://glumpy.readthedocs.org/en/latest/index.html

**Comment by techtonik** [comment]
Looks good.
