### ISSUE TITLE
installation fails under windows 8 due to compilation error

### ISSUE THREAD

**Issue by BogusLogin** [glumpy/glumpy#45]
When I run the setup.py script the installation process fails, the final error message is
    ...
    build\temp.win-amd64-2.7\Release\glumpy\ext\sdf\_sdf.o:_sdf.c:(.text+0x4d41): undefined reference to `_imp__PyErr_SetString'
    c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: build\temp.win-amd64-2.7\Release\glumpy\ext\sdf\_sdf.o: bad reloc address 0x0 in section `.data'
    collect2.exe: error: ld returned 1 exit status
    error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1

I put the whole output on [pastebin](http://pastebin.com/P8dvGVBK)

**Comment by rougier** [comment]
It probably means either you did not install the python dev files or that the setup script did not find them. From the full ouptut, it's like also the library is not linked with the python library. Did you ever have such problem with other cython script ? (the sdf/cython is needed for font only)

**Comment by BogusLogin** [comment]
No, I encountered this error for the first time. To be honest I'm sick of Windows atm, so I won't investigate this problem any further. I know this isn't very satisfying, but at least this thread creates awareness of the problem.

**Comment by rougier** [comment]
Ok. I do not have access to Windows so it's a bit difficult to debug for me.
