### ISSUE TITLE
geopositon library in transform library problem

### ISSUE THREAD

**Issue by nemesis-439** [glumpy/glumpy#63]
Hello,

I tried demo mandelbrot.py and I have Python error message ->  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.10-x86_64.egg/glumpy/transforms/__init__.py", line 11, in <module>
    from . geoposition import GeoPosition
ImportError: No module named geoposition

When I see to Git repository Glumpy/transformation then I think that geoposition library was erase.

Please where I can found geoposition library or how can to solve my problem with demo program mandelbrot.py?

Thanks
Karel Simecek
Czech republic

**Comment by rougier** [comment]
Oops, thank. I forgot to add the files...
