### ISSUE TITLE
Incorrect text placement with `font-agg.py` and `font-sdf.py`

### ISSUE THREAD

**Issue by jdugge** [glumpy/glumpy#68]
When I run the  `font-agg.py` and `font-sdf.py` examples, all the text is printed on the very bottom of the window, instead of being spread out (see attached screenshots). `font-atlas.py` works fine.

I'm using `glumpy` 1.0.6 cloned from the GitHub repository.

Output from `inxi -b`:
```
System:    Host: desktop Kernel: 3.19.0-32-generic x86_64 (64 bit)
           Desktop: Cinnamon 2.8.6  Distro: Linux Mint 17.3 Rosa
Machine:   Mobo: MSI model: Z170-A PRO (MS-7971) v: 1.0
           Bios: American Megatrends v: 1.50 date: 09/02/2015
CPU:       Quad core Intel Core i5-6400 (-MCP-) speed/max: 800/2701 MHz
Graphics:  Card: Intel Device 1912
           Display Server: X.Org 1.17.1 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.0hz
           GLX Renderer: Mesa DRI Intel Skylake DT GT2
           GLX Version: 3.0 Mesa 10.5.9
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169
Drives:    HDD Total Size: 500.1GB (5.7% used)
Info:      Processes: 184 Uptime: 3 min Memory: 667.3/15967.3MB
           Client: Shell (bash) inxi: 2.2.28
```

Let me know if there's anything I can do to help track down the issue.

![image](https://cloud.githubusercontent.com/assets/2399255/13021490/d1b6d828-d1db-11e5-8c05-eb5a95b18ebb.png)

![image](https://cloud.githubusercontent.com/assets/2399255/13021499/e0bc2cf6-d1db-11e5-9178-d059e51113df.png)

**Comment by rougier** [comment]
Thanks for the report. I suspect this is related to a float texture problem.

Could you try to add `origin='local'` in the collection declaration in each example (his should move the storage of the `origin` from the texture to the buffer). If this works, I will try to fix the collection.

**Comment by jdugge** [comment]
Unfortunately, that doesn't change the output. I also tried out the `material-colors.py` example, and I get the same output as rossant did in #31, so I guess this issue is actually a duplicate of that.

I used a different computer this time, which has an nVidia graphics chip:

```
System:    Host: T410 Kernel: 3.13.0-24-generic x86_64 (64 bit) Desktop: Gnome Distro: Linux Mint 17 Qiana
Machine:   System: LENOVO product: 2522FY3 version: ThinkPad T410
           Mobo: LENOVO model: 2522FY3 Bios: LENOVO version: 6IET85WW (1.45 ) date: 02/14/2013
CPU:       Dual core Intel Core i7 CPU M 620 (-HT-MCP-) clocked at 1199.00 MHz 
Graphics:  Card: NVIDIA GT218M [NVS 3100M] X.Org: 1.15.1 driver: nvidia Resolution: 1440x900@60.1hz 
           GLX Renderer: NVS 3100M/PCIe/SSE2 GLX Version: 3.3.0 NVIDIA 340.96
Network:   Card-1: Intel Centrino Ultimate-N 6300 driver: iwlwifi 
           Card-2: Intel 82577LM Gigabit Network Connection driver: e1000e 
Drives:    HDD Total Size: 628.1GB (79.8% used)
Info:      Processes: 224 Uptime: 3 days Memory: 3902.8/7845.3MB Client: Shell inxi: 1.8.4 
```

**Comment by rougier** [comment]
Interesting. Do you know if there are other examples that do not work ?
For example, what is the output of the float-texture.py example ? gradient or solid color ?

**Comment by jdugge** [comment]
Solid black and white:

![image](https://cloud.githubusercontent.com/assets/2399255/13027971/421ad170-d261-11e5-8924-531e43ba2de5.png)

**Comment by rougier** [comment]
Ok, can you replace:
```
program['texture'] = T.astype(np.float32).reshape(32,32)
```
by
```
program['texture'] = (T.astype(np.float32).reshape(32,32)).view(gloo.TextureFloat2D)
```

**Comment by jdugge** [comment]
Yup, that did the trick for `float-texture.py`:

![image](https://cloud.githubusercontent.com/assets/2399255/13028005/4ef29a76-d262-11e5-8651-62f1a0f9d6b4.png)

**Comment by rougier** [comment]
Ok, thanks. That might be probably the problem with the glyph collection as well. 

A probable fix could be to change the Texture2D by a TextureFloat2d at [line 518](https://github.com/glumpy/glumpy/blob/master/glumpy/graphics/collections/base_collection.py#L518) in the [base_collection.py](https://github.com/glumpy/glumpy/blob/master/glumpy/graphics/collections/base_collection.py)

**Comment by jdugge** [comment]
That's it:

![image](https://cloud.githubusercontent.com/assets/2399255/13028031/488b2f08-d263-11e5-82a7-23d328bb751e.png)

Great, thanks for your super quick help (and amazing project)!

**Comment by jdugge** [comment]
I just checked `material-colors.py` and `font-sdf.py`, and they also workly nicely now.

**Comment by rougier** [comment]
Nice ! Can you make a PR ?
