### ISSUE TITLE
Key constants are not keymap-aware

### ISSUE THREAD

**Issue by gspr** [glumpy/glumpy#70]
This is probably no high priority, but perhaps the key constants in `app.window.key` could be made keypmap-aware.

As an example, `app.window.key.A` is `97`, but on my system hitting the "a" key creates an event with the data `65`.

**Comment by rougier** [comment]
It depends on what you want to achieve. Have a look at the [app-events.py](https://github.com/glumpy/glumpy/blob/master/examples/app-events.py) example. You'll see there is a `on_key_press` event (keycode) and a `on_character` (actual letter).

**Comment by gspr** [comment]
Ugh, this just proves that I'm blond and/or an idiot. Thank you, and sorry to waste your time.
