### ISSUE TITLE
PyQt5 resize signals not captured?

### ISSUE THREAD

**Issue by TheBB** [glumpy/glumpy#72]
I tried running the `gloo-cube.py` example with the qt5 backend, but I can't get resizing to work properly. I tried attaching a homemade print function to `window._native_window.resizeGL` as well, but it's not being called upon resizing the window.

Am I missing something?

**Comment by rougier** [comment]
What do you get from the `on_resize(width, height)` function in the example ? Is it called ?

**Comment by TheBB** [comment]
No, it's not called.

Are you saying you can't reproduce?

**Comment by rougier** [comment]
No, I need to check on my system, but qt5 is not installed

**Comment by rougier** [comment]
Ok, I've the same problem. I'm looking into it.
You can also investigate using the `app-events.py` example.

**Comment by TheBB** [comment]
Ok, thanks!

**Comment by rougier** [comment]
Do you have a simple qt5 python program where the resizeGL is actually called by any chance (no glumpy at all, only qt5) ?

**Comment by TheBB** [comment]
This seems to work. I was experimenting with embedding the glumpy window in a larger Qt5 application.

```python
    from PyQt5.QtWidgets import QApplication, QMainWindow
    from PyQt5.QtOpenGL import QGLWidget

    WITH_WINDOW = True

    def handler(*args, **kwargs):
        print('resize', args, kwargs)

    app = QApplication([])

    glwidget = QGLWidget()
    glwidget.resizeGL = handler

    if WITH_WINDOW:
        window = QMainWindow()
        window.setCentralWidget(glwidget)
        window.show()
    else:
        glwidget.show()

    app.exec_()
```

**Comment by TheBB** [comment]
I think I figured it out. You have to call `window._native_window.show()` **after** you have attached the event handlers. #73

**Comment by rougier** [comment]
Humm, no idea of the reason behind but many thansk for the fix.
