### ISSUE TITLE
Empty data-type error when running the cube example

### ISSUE THREAD

**Issue by MetaDev** [glumpy/glumpy#77]
When I run the code below:

from glumpy import app, gloo, gl

vertex = """
         vec2 attribute position;
         void main()
         {
             gl_Position = vec4(position, 0.0, 1.0);
         } """

fragment = """
           uniform vec4 color;
           void main() {
               gl_FragColor = color;
           } """

quad = gloo.Program(vertex, fragment, count=4)
quad['position'] = [(-0.5, -0.5),
                    (-0.5, +0.5),
                    (+0.5, -0.5),
                    (+0.5, +0.5)]
quad['color'] = 0,0,0,1
window = app.Window()

@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)

app.run()

--------------------------------------------
I get following error:

    quad = gloo.Program(vertex, fragment, count=4)

  File "/Users/Harald/anaconda/lib/python3.5/site-packages/glumpy/gloo/program.py", line 102, in __init__
    self._buffer = np.zeros(self._count, dtype=dtype).view(VertexBuffer)

TypeError: Empty data-type
---------------------------------------------

Python 3.5.1 64bits, Qt 5.5.0, PyQt5 5.5 on Darwin

My dependencies:

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
numpy >=1.7     :  1.11.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.0.0 (OK)
pyflakes >=0.6.0:  1.0.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)

**Comment by rougier** [comment]
I think you should write `attribute vec2 position;`(instead of `vec2 attribute position`)

**Comment by MetaDev** [comment]
OK, that was straightforward. Maybe change it than on http://glumpy.readthedocs.io/en/latest/quickstart.html. that's where I copied it from.

**Comment by rougier** [comment]
Done.
