### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by lmjohns3** [glumpy/glumpy#8]
Glumpy is such an awesome tool, thanks for creating it!

Recently I switched my work over to Python 3 and now I cannot install glumpy.

It seems from the installation errors that it would be pretty straightforward to do, maybe even by using the 2to3 tool in setup.py. But I'd love to have glumpy working in Python 3 if possible!

**Comment by ph03** [comment]
+1 for a python3 version (I need py3 to be able to integrate this in our py3 codebase..)

I already ported most of the library successfully using 2to3, however, there are still some issues to fix. I could share this if you are interested in it?

**Comment by rougier** [comment]
oh yes, for sure.

**Comment by rougier** [comment]
Done.
