### ISSUE TITLE
Point and line size dropped when using multiple windows

### ISSUE THREAD

**Issue by mibieri** [glumpy/glumpy#83]
There was an issue when using multiple windows recently. It was fixed so that it is possible to use multiple windows now. But still, there seem to be a problem: At least point size and probably line size is not used properly.

The following file demonstrates the issue: https://groups.google.com/group/glumpy-users/attach/8d6a06acc24c3/app-two-programs-two-windows.py?part=0.1&authuser=0&view=1

One windows correctly gets a large point, the other one incorecctly just a very small dot.

**Comment by rougier** [comment]
This is the source linked from the post above:

```
# -----------------------------------------------------------------------------
# Copyright (c) 2009-2016 Nicolas P. Rougier. All rights reserved.
# Distributed under the (new) BSD License.
# -----------------------------------------------------------------------------
import numpy as np
from glumpy import gl, app, gloo


vertex = """
attribute vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0.0, 1.0);
    gl_PointSize = 30.0;
}
"""

fragment1 = """
void main() {
    gl_FragColor = vec4(0.0, 0.0, 1.0, 1.0);
}
"""

fragment2 = """
void main() {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
"""


program1 = gloo.Program(vertex, fragment1)  # blue on the left
program1['a_position'] = np.zeros((1,2),dtype=np.float32) + 0.5
program2 = gloo.Program(vertex, fragment2)  # red on the right
program2['a_position'] = np.zeros((1,2),dtype=np.float32) - 0.5


window1 = app.Window()
@window1.event
def on_draw(dt):
    window1.clear()
    program1.draw(gl.GL_POINTS)


window2 = app.Window()
@window2.event
def on_draw(dt):
    window2.clear()
    program2.draw(gl.GL_POINTS)

app.run()
```

**Comment by rougier** [comment]
You should declare your programs in a dedicated event `on_init` event:

```
@window1.event
def on_init():
    program1 = gloo.Program(vertex, fragment1)  # blue on the left
    program1['a_position'] = np.zeros((1,2),dtype=np.float32) + 0.5

@window2.event
def on_init():
    program2 = gloo.Program(vertex, fragment1)  # blue on the left
    program2['a_position'] = np.zeros((1,2),dtype=np.float32) + 0.5
```

**Comment by mibieri** [comment]
Unfortunately, that's not possible in my case. I first open a window that contains nothing, and then plots will be shown in that window depending on user input.

This works as follows: For each new plot, I create a new gloo.Program. The window holds a list of all those program. Upon on_draw, it will call program.draw(gl.GL_xxx) for each of the programs. 

Is that a bad practice? Another option would be to create a program for each drawing type upon on_init, and then subsequently add more and more data to the drawing upon user input.

(See also the other issue I opened yesterday, same situation there: https://github.com/glumpy/glumpy/issues/84 )

**Comment by rougier** [comment]
Each time you create a program, you need to be sure to be in the right GL context because there are two different context, one for each window. One possibility it to explicitly `activate` the window before creating the program.

**Comment by mibieri** [comment]
Unfortunately, that does not help at all. I tried to insert 'activate' and also use a semaphore to make sure contexts are not accidentally messed up, but the blue point is still a very small dot.

`# -----------------------------------------------------------------------------
# Copyright (c) 2009-2016 Nicolas P. Rougier. All rights reserved.
# Distributed under the (new) BSD License.
# -----------------------------------------------------------------------------
import numpy as np
from glumpy import gl, app, gloo
from threading import BoundedSemaphore

vertex = """
attribute vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0.0, 1.0);
    gl_PointSize = 30.0;
}
"""

fragment1 = """
void main() {
    gl_FragColor = vec4(0.0, 0.0, 1.0, 1.0);
}
"""

fragment2 = """
void main() {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
"""
sem = BoundedSemaphore()

window1 = app.Window()
window2 = app.Window()

@window1.event
def on_init():
    global program1
    with sem:
        window1.activate()
        program1 = gloo.Program(vertex, fragment1)  # blue on the left
        program1['a_position'] = np.zeros((1,2),dtype=np.float32) + 0.5

@window2.event
def on_init():
    global program2
    with sem:
        window2.activate()
        program2 = gloo.Program(vertex, fragment2)  # red on the right
        program2['a_position'] = np.zeros((1,2),dtype=np.float32) - 0.5

@window1.event
def on_draw(dt):
    with sem:
        window1.activate()
        window1.clear()
        program1.draw(gl.GL_POINTS)

@window2.event
def on_draw(dt):
    with sem:
        window2.activate()
        window2.clear()
        program2.draw(gl.GL_POINTS)

app.run()`

**Comment by rougier** [comment]
I just fixed it hopefully and you don't need the `sem` (normally).

**Comment by mibieri** [comment]
Seems to work! Thanks a lot.
