### ISSUE TITLE
python 2.7 with  windows 10 need freetype.

### ISSUE THREAD

**Issue by catafest** [glumpy/glumpy#85]
Error I got ( from https://github.com/glumpy/glumpy/blob/master/examples/smoke/smoke.py)

```
 ...in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found
```

the python 2.7 don't wat to install freetype  
http://stackoverflow.com/questions/39025319/hot-to-fix-python-freetype-under-windows-10

**Comment by rougier** [comment]
It seems that Freetype bindings are installed but not the freetype library. Do you know if it is installed on your system ?

**Comment by catafest** [comment]
I think so. I tested on Windows 10. 
I install the freetype-2.3.5-1-setup.exe.
I put the .dll into System32 ( I don't agree with this way to solve the isuse).

Can you help me?

Sorry about this aditional question: Way is need to have it? I tested the vispy example test and working well.

**Comment by rougier** [comment]
Problably the ctype did not find the .dll for some reason. Do you known where it is installed on your system ?

As for glumpy, it is not strictly mandatory but I need to modify the library to make it really optional.

**Comment by catafest** [comment]
The windows setup put it on C:\Program Files (x86)\GnuWin32.
The freetype6.dll -> system32 ...
any info ?

**Comment by rougier** [comment]
Can you look into https://github.com/rougier/freetype-py/issues/27 and check if is solves your problem ?

**Comment by louistheurier** [comment]
Hi
Try to rename the file to freetype.dll instead of freetype6.dll

**Comment by CharlesScoville** [comment]
I've more or less run into this issue too. However, I'm on Windows 7 x64 using Python 3.x. 

I solved my problems by downloading a x64 version of freetype, (cnet's download.com, unfortunately) then dropping a renamed version of the main dll directly into my Python install directory. After this I got an almost identical error, this time not finding the GLFW libs. Solved this second issue mostly the same way, though through a more official vector for the files.

In any case, smoke.py works for me now. (:3)

p.s. 
[This](https://github.com/ubawurinna/freetype-windows-binaries) looks like a better place to get the Windows x64 versions of freetype. Haven't tried it yet though.

**Comment by rougier** [comment]
Thanks for the information. Could you write a (small) howto for windows in the INSTALL file ?

**Comment by CharlesScoville** [comment]
> Could you write a (small) howto for windows in the INSTALL file ?

Yeah, sure, probably. I'll want to start over with a clean setup first though to make sure it's reproducible.

Is it "glumpy/doc/installation.rst" or something else? (Couldn't find a file specifically called "INSTALL")
