### ISSUE TITLE
Numpy missing in transforms/translate.py

### ISSUE THREAD

**Issue by mibieri** [glumpy/glumpy#86]
Seems that there are some problems with transforms/translate.py:

First, the import of numpy is missing in transforms/translate.py, what leads to an error on line 59. (NameError: name 'np' is not defined)

Second (after inserting numpy import by myself), it will lead to a shader compile error:

```
Error in Vertex shader 2 (<string>)
 -> ')' : syntax error: syntax error

 ...
 014 vec3 forward_2(float x, float y, float z)
 015 { return vec3(x,y,z) + translate_translate_2); }
 016 
 017 vec3 forward_2(vec3 P)
 018 { return P + translate_translate_2; }
 ...
```

I can add more details if necessary.

**Comment by rougier** [comment]
Yes please. Can you post a minimal example that show the bug ?

**Comment by mibieri** [comment]
For example, if you want to use Translate instead of PanZoom in the transform-pan-zoom.py example:

```
import numpy as np
from PIL import Image
from glumpy import app, gl, glm, gloo, data
from glumpy.transforms import PanZoom, Position, Translate

vertex = """
    attribute vec2 position;
    attribute vec2 texcoord;
    varying vec2 v_texcoord;
    void main()
    {
        gl_Position = <transform>;
        v_texcoord = texcoord;
    }
"""

fragment = """
    uniform sampler2D texture;
    varying vec2 v_texcoord;
    void main()
    {
        gl_FragColor = texture2D(texture, v_texcoord);
    }
"""

window = app.Window(width=800, height=800)

@window.event
def on_draw(dt):
    window.clear()
    program.draw(gl.GL_TRIANGLE_STRIP)

@window.event
def on_key_press(key, modifiers):
    if key == app.window.key.SPACE:
        transform.reset()

program = gloo.Program(vertex, fragment, count=4)
program['position'] = [(-1,-1), (-1,1), (1,-1), (1,1)]
program['texcoord'] = [( 0, 1), ( 0, 0), ( 1, 1), ( 1, 0)]
program['texture'] = data.get("lena.png")

transform = Translate(Position("position"))
program['transform'] = transform
window.attach(transform)

app.run()
```

**Comment by rougier** [comment]
For translate + zoom in 2D, you can use the pan-zoom transform.
For rotate + zoom in 3D, you can use the trackball transform.

But you want translate + zoom in 3D, it that correct ?

**Comment by mibieri** [comment]
Yes exactly. The problem is, that Trackball always zooms in to the same point. So maybe there could be a way to zoom in to the point (or rather line) projected by the mouse pointer. It would then work like the scrolling action of PanZoom, while the dragging action would result in rotate.

**Comment by rougier** [comment]
Ok, makes sense now. But that's another story because you need to define properly the transform. It is not yet implemented in glumpy but if you find some papers or blog post that specify such interaction, I can try to implement it.

**Comment by mibieri** [comment]
I think the transform I proposed yesterday is not necessary and fully
covered by the existing trackball: You can always rotate the feature of
interest into the middle of the screen and then zoom into it.

However, it's getting difficult when visualizing structures that resemble a
cave. A transform/interaction like in 3D ego perspective games would then
be very useful to travel around in such a cave-like structure. (WASD to
walk + mouse to look around, while W/S could be replaced by the scroll
wheel.)

**Comment by rougier** [comment]
I fear this will require a new transform. But first you have to specify how each mouse move and buttons will impact your transform and you might also need the keyboard. You might want to look at vispy where I think there is such transform and we could adapt it.
