### ISSUE TITLE
Problems getting app-simple.py to run

### ISSUE THREAD

**Issue by RodogInfinite** [glumpy/glumpy#91]
I started by having a similar problem to https://github.com/glumpy/glumpy/issues/25. I installed glfw using `git clone https://github.com/glfw/glfw.git` and it installed into my home directory. When I tried ~/glumpy/examples$`./app-simple.py` from the terminal I received 

> bash: ./app-simple.py: Permission denied

When I used `python app-simple.py` from the terminal I received the following 

> Traceback (most recent call last):
>   File "app-simple.py", line 7, in <module>
>     window = app.Window()
>   File "/home/rodoginfinite/anaconda2/lib/python2.7/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 150, in __new__
>     backend = use(name)
>   File "/home/rodoginfinite/anaconda2/lib/python2.7/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 116, in use
>     importlib.import_module(name)
>   File "/home/rodoginfinite/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/rodoginfinite/anaconda2/lib/python2.7/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/app/window/backends/backend_glfw.py", line 82, in <module>
>     from glumpy.ext import glfw
>   File "/home/rodoginfinite/anaconda2/lib/python2.7/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/ext/glfw.py", line 60, in <module>
>     raise OSError('GLFW library not found')
> OSError: GLFW library not found

and when I ran from PyCharm I received the following 

> Traceback (most recent call last):
>   File "/home/rodoginfinite/glumpy/examples/app-simple.py", line 5, in <module>
>     from glumpy import app
> ImportError: No module named glumpy

I modified /home/rodoginfinite/anaconda2/lib/python2.7/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/app/__init__.py line 34 to `__backend__ = 'glfw' ` and changed line 49 to `def use(backend, api='GL', major=3, minor=2, profile='core'):` and ran `python app-simple.py` in the terminal and received 

> Traceback (most recent call last):
>   File "app-simple.py", line 7, in <module>
>     window = app.Window()
>   File "/home/rodoginfinite/anaconda2/lib/python2.7/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 184, in __new__
>     window = __backend__.Window(*args, **kwargs)
> AttributeError: 'str' object has no attribute 'Window'

I'm probably making noob errors, but I've been trying to solve it for a while now. Any help would be appreciated. Also, I have PyQt and Qt 5 and was wondering what would be necessary to get that working as an alternative. Would it be something like `__backend__= 'PyQt'` and `def use(backend, api = 'Qt' , major = int , minor = int, profile = 'core')` with the ints replaced by version numbers?

**Comment by RodogInfinite** [comment]
I had forgotten to add the path in PyCharm and that's why it couldn't find the module. I'm now running app-simple.py in PyCharm and getting this traceback 

> 
> Traceback (most recent call last):
>   File "/home/rodoginfinite/glumpy/examples/app-simple.py", line 5, in <module>
>     from glumpy import app
>   File "/home/rodoginfinite/glumpy/glumpy/__init__.py", line 7, in <module>
>     from . import app
>   File "/home/rodoginfinite/glumpy/glumpy/app/__init__.py", line 23, in <module>
>     from . console import Console
>   File "/home/rodoginfinite/glumpy/glumpy/app/console.py", line 7, in <module>
>     from glumpy import gl, glm, gloo
>   File "/home/rodoginfinite/glumpy/glumpy/gloo/__init__.py", line 5, in <module>
>     from . atlas import Atlas
>   File "/home/rodoginfinite/glumpy/glumpy/gloo/atlas.py", line 9
> SyntaxError: Non-ASCII character '\xcc' in file /home/rodoginfinite/glumpy/glumpy/gloo/atlas.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by rougier** [comment]
This error is because you're using python 2. Coudl you try python 3 instead ?

As for your first error, it means you have to install the GLFW3 library. Depending on your system, you can install it using your package manager or directly from glfw.org

**Comment by RodogInfinite** [comment]
I installed Anaconda3 successfully and the traceback from my second post reverted back to the following 

> 
> Traceback (most recent call last):
>   File "/home/rodoginfinite/glumpy/examples/app-simple.py", line 7, in <module>
>     window = app.Window()
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/glumpy-1.0.6-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 184, in __new__
>     window = __backend__.Window(*args, **kwargs)
> AttributeError: 'str' object has no attribute 'Window'

I installed glfw using `git clone https://github.com/glfw/glfw.git` and after your reply I threw in a `pip install --upgrade glfw` and got 

> Requirement already up-to-date: glfw in ./anaconda3/lib/python3.5/site-packages

**Comment by rougier** [comment]
I think you need to uninstall glumpy and try the current github version.
And I may need to make a release since I suspect Anaconda is using an old version of glumpy.

**Comment by RodogInfinite** [comment]
Glumpy wasn't included in Anaconda's Python 3.5 site-packages. I started from scratch and re-installed Ubuntu. Here's my log so far

Install Anaconda3- 4.2.0
	https://www.continuum.io/downloads
	`bash Anaconda3-4.2.0-Linux-x86_64.sh`

Install pip3 
        `sudo apt-get install python3-setuptools`
	`sudo easy_install3 pip`

Install git
	`sudo apt-get install git`

Install glumpy
	`git clone https://github.com/glumpy/glumpy.git`

Install glfw
	`git clone https://github.com/glfw/glfw.git`

Upgrade numpy
	`sudo pip install --upgrade numpy`

Upgrade PyOpenGL
	`sudo pip install --upgrade PyOpenGL`

Install ffmpeg
	`sudo apt-get install ffmpeg`

Upgrade Cython
	`sudo pip install --upgrade cython`

Upgrade Triangle
	`sudo pip install --upgrade triangle`

Install pycharm
	https://www.jetbrains.com/pycharm/download/#section=linux
	`bash pycharm.sh`

Moved the glumpy and glfw file folders to: ~/anaconda3/lib/python3.5/site-packages (Not sure if this was the right thing to do)and updated the site packages external library in PyCharm.

ran app-simple.py in PyCharm and got this traceback
 

> Traceback (most recent call last):
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/glumpy/examples/app-simple.py", line 5, in <module>
>     from glumpy import app
> ImportError: cannot import name 'app'
> 

I located glumpy/glumpy/app/__init__.py and modified line 34 and 49 to

```
# Default clock
__clock__ = None

# Active windows
__windows__ = []

# Current backend
__backend__ = 'glfw'


__running__ = False


# --------------------------------------------------------------------- fps ---
def fps():
    """
    Get FPS from the default clock.
    """
    return __clock__.get_fps()


# --------------------------------------------------------------------- use ---
def use(backend, api='GL', major=3, minor=2, profile='core'):
```

I tried to run app-simple.py again and got the same traceback 


I moved glfw and glumpy back to the Downloads folder and reconnected glumpy as an external library in PyCharm from its new location and received the following

```
Traceback (most recent call last):
  File "/home/rodoginfinite/Downloads/glumpy/examples/app-simple.py", line 5, in <module>
    from glumpy import app
  File "/home/rodoginfinite/Downloads/glumpy/glumpy/__init__.py", line 7, in <module>
    from . import app
  File "/home/rodoginfinite/Downloads/glumpy/glumpy/app/__init__.py", line 14, in <module>
    from glumpy import gl
  File "/home/rodoginfinite/Downloads/glumpy/glumpy/gl.py", line 8, in <module>
    import OpenGL
ImportError: No module named 'OpenGL'
```

I connected glfw as an external library in PyCharm and there was no change in the traceback.

I ran python app-simple.py from the terminal and got the following traceback 

```
Traceback (most recent call last):
  File "app-simple.py", line 5, in <module>
    from glumpy import app
ImportError: No module named glumpy
```
I'm continuing my investigation

**Comment by RodogInfinite** [comment]
I downloaded PyOpenGL from https://sourceforge.net/projects/pyopengl/files/PyOpenGL/
and installed using `python setup.py install` in the terminal

I reran app-simple.py in PyCharm and the traceback changed to 

> Traceback (most recent call last):
>   File "/home/rodoginfinite/Downloads/glumpy/examples/app-simple.py", line 5, in <module>
>     from glumpy import app
>   File "/home/rodoginfinite/Downloads/glumpy/glumpy/__init__.py", line 7, in <module>
>     from . import app
>   File "/home/rodoginfinite/Downloads/glumpy/glumpy/app/__init__.py", line 14, in <module>
>     from glumpy import gl
>   File "/home/rodoginfinite/Downloads/glumpy/glumpy/gl.py", line 30, in <module>
>     from OpenGL import contextdata
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/OpenGL/contextdata.py", line 71
>     except (KeyError,TypeError,ValueError), err:
>                                           ^
> SyntaxError: invalid syntax

**Comment by RodogInfinite** [comment]
I installed triangle with git clone https://github.com/drufat/triangle.git and installed using python setup.py install and installed Cython-0.24.1-cp35-cp35m-manylinux1_x86_64.whl from https://pypi.python.org/pypi/Cython/. I had to use sudo python setup.py install because of permission denials. Everything seemed to be copying well until it terminated with the following fatal error.

> creating build/temp.linux-x86_64-2.7/home/rodoginfinite/Downloads/Cython-0.24.1

> creating build/temp.linux-x86_64-2.7/home/rodoginfinite/Downloads/Cython-0.24.1/Cython
> creating build/temp.linux-x86_64-2.7/home/rodoginfinite/Downloads/Cython-0.24.1/Cython/Plex
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c /home/rodoginfinite/Downloads/Cython-0.24.1/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/home/rodoginfinite/Downloads/Cython-0.24.1/Cython/Plex/Scanners.o
> /home/rodoginfinite/Downloads/Cython-0.24.1/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by rougier** [comment]
What happens if you type directly `from OpenGL import contextdata` in the python console ?

**Comment by rougier** [comment]
For your last error, it means you have to install the dev package for Python (something like `Python3-dev` under ubuntu)

**Comment by RodogInfinite** [comment]
> rodoginfinite@rodoginfinite-desktop:~$ python
> Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from OpenGL import contextdata
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/OpenGL/contextdata.py", line 71
>     except (KeyError,TypeError,ValueError), err:
>                                           ^
> SyntaxError: invalid syntax
>

**Comment by RodogInfinite** [comment]
as for the other error, I downloaded the python3-dev_3.2.3-0ubuntu1_all.deb file from http://packages.ubuntu.com/precise/all/python3-dev/download and installed using ubuntu's software installer. Same fatal error occurs when trying to install Cython's setup.py. If I forget to use sudo before python setup.py install then this pops up

> Unable to find pgen, not compiling formal grammar.
> running install
> running bdist_egg
> running egg_info
> writing top-level names to Cython.egg-info/top_level.txt
> error: [Errno 13] Permission denied: 'Cython.egg-info/top_level.txt'

**Comment by rougier** [comment]
Can you try `sudo apt-get install cython3` ?

**Comment by RodogInfinite** [comment]
using `sudo apt-get install cython3` seems to be successful. No fatal errors reported

**Comment by rougier** [comment]
Does the app-simple.py example run properly now ?

**Comment by RodogInfinite** [comment]
No, same traceback error. I've been afk and haven't been able to look deeper into it yet

> 
> > rodoginfinite@rodoginfinite-desktop:~/Downloads/glumpy/examples$ python app-simple.py
> Traceback (most recent call last):
>   File "app-simple.py", line 5, in <module>
>     from glumpy import app
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/glumpy-1.0.6-py3.5-linux-x86_64.egg/glumpy/__init__.py", line 7, in <module>
>     from . import app
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/glumpy-1.0.6-py3.5-linux-x86_64.egg/glumpy/app/__init__.py", line 14, in <module>
>     from glumpy import gl
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/glumpy-1.0.6-py3.5-linux-x86_64.egg/glumpy/gl.py", line 30, in <module>
>     from OpenGL import contextdata
>   File "/home/rodoginfinite/anaconda3/lib/python3.5/site-packages/OpenGL/contextdata.py", line 71
>     except (KeyError,TypeError,ValueError), err:
>                                                                    ^
> SyntaxError: invalid syntax

**Comment by RodogInfinite** [comment]
I found this http://stackoverflow.com/questions/7520690/syntax-error-with-keyerror-in-python-3-2 and changed the commas in lines 71, 93, and 128 to 'as' and now the traceback is sending me to another file in OpenGL is there an OpenGL package specifically for Python 3?

**Comment by RodogInfinite** [comment]
If I do this 
```
from glumpy import app
app.use('glfw')
window = app.Window()

@window.event
def on_draw(dt):
    window.clear()

app.run()
```


Then I get OSError: GLFW library not found

**Comment by rougier** [comment]
Can you try:
```
import ctypes.util
print(ctypes.util.find_library("glfw"))
print(ctypes.util.find_library("glfw3"))
```

**Comment by RodogInfinite** [comment]
None
None

**Comment by rougier** [comment]
This means ctypes cannot find the glfw3 library. Do you know where it is installed ?

**Comment by RodogInfinite** [comment]
It's in anaconda3/lib/python3.5/site-packages

I backtracked a bit and went to http://www.glfw.org/docs/latest/compile.html#compile_deps_x11

I installed xorg-dev 
        `sudo apt-get install xorg-dev`
I tried to install gcc and make, but they were already up to date

**Comment by rougier** [comment]
But do you know where is the `libglfw.so` installed ?

**Comment by RodogInfinite** [comment]
libglfw-dev wasn't installed so I went ahead with a sudo apt-get install libglfw-dev. 

I ran app-simple.py again and it now says I don't have glfw3 I have 2.7.9. I downloaded the glfw-3.2.1 file, it's sitting in my downloads folder. 

I deleted the glfw file folders in anaconda3/lib/python3.5/site-packages

I followed this guide http://stackoverflow.com/questions/17768008/how-to-build-install-glfw-3-and-use-it-in-a-linux-project 
 installed CMake `sudo apt-get cmake` and ran `cmake -G "Unix Makefiles"` ran `make` and ran `sudo make install`

ran python app-simple.py again and it still says I have 2.7.9

**Comment by rougier** [comment]
Don't you have a libglfw3 ?

**Comment by RodogInfinite** [comment]
my noob is showing... uninstalled libglfw-dev and installed libglfw3-dev 

getting this now 

> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> [w] b'GLX: Failed to create context: GLXBadFBConfig'
> [x] Window creation failed
>

**Comment by rougier** [comment]
Can you try to run the app-simpel.py directly from the console ?

**Comment by RodogInfinite** [comment]
```
>>> from glumpy import app
>>> window = app.Window()
```

> Segmentation fault (core dumped)

**Comment by rougier** [comment]
You can also try `python app-simple.py -b freeglut`

**Comment by rougier** [comment]
Or `python app-simple.py -b pyglet` (requires pyglet though)

**Comment by RodogInfinite** [comment]
I didn't purge the driver and tried `python app-simple.py -b freeglut`. It works. I get a window with a black background and the following is displayed in the terminal:

[i] Using GLFW (GL 4.5)
[i] Running at 60 frames/second

**Comment by RodogInfinite** [comment]
I'm going to compile this log into a guide and start from scratch again to see if I can get it up and running in one go. Thank you for your help! 

Is there a place to go where it would be appropriate to post a running log as I try to get PyQt with Qt5 to work as a backend afterwards?

**Comment by RodogInfinite** [comment]
side note: I ran python `app-simple.py` and got the same output as when I used freeglut as a backend. I must have just had to restart my computer after making all of those changes
