### ISSUE TITLE
Drawing into framebuffer: How to clear it?

### ISSUE THREAD

**Issue by mibieri** [glumpy/glumpy#93]
I started with the gloo-picking example: [https://github.com/glumpy/glumpy/blob/master/examples/gloo-picking.py](url) 

What I wonder: How does it work with clearing `framebuffer`? I adapted the code into my code, and now, upon redraw, the old graphics just stays in the buffer. This does not really surprise me, since I never clear that buffer.

I just wonder whether one can give me a quick hint on that, else I'll try to distill a short code example to show the problem. (It's nested in a large code, so that won't be very easy...)

EDIT: Or more generally speaking, shouldn't there be a way to clear a `Texture`, and why does it happen (magically) in gloo-picking? Questions... ;-)

**Comment by rougier** [comment]
When the framebuffer is bound, a `glClear` should be enough to clear the framebuffer. Is it not the case ?

**Comment by mibieri** [comment]
Yes, that was the problem. I think I was confused because I was looking for a glumpy-way to do, instead of using plain OpenGL.

Thanks a lot! :-)
