### ISSUE TITLE
Obsolete attributes in Qt5

### ISSUE THREAD

**Issue by electronicLight** [glumpy/glumpy#99]
Hello!

I'm using glumpy with Qt5 backend. When I spin the mouse wheel, this exception raises:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/backends/backend_qt5.py", line 288, in wheel_event
    if event.orientation == QtCore.Qt.Horizontal:
AttributeError: 'QWheelEvent' object has no attribute 'orientation'
```

It happens because orientation is no longer an attribute of QWheelEvent in Qt5 as you can see here [http://doc.qt.io/qt-5/qwheelevent-obsolete.html](http://doc.qt.io/qt-5/qwheelevent-obsolete.html).

Futhermore, that is the function from which the exception comes:

```
        def wheel_event(event):
            if event.orientation == QtCore.Qt.Horizontal:
                offset_x = event.delta()
                offset_y = 0
            else:
                offset_x = 0
                offset_y = event.delta()
            x = event.pos().x()
            y = event.pos().y()
            self.dispatch_event("on_mouse_scroll", x, y, offset_x/10.0, offset_y/10.0)
```
Please, note that delta() is either no longer a method of QWheelEvent. I think that should be easy to fix. Could you do this?

Thank you so much.

Glumpy is a great and "must have" package, btw.

**Comment by rougier** [comment]
Thanks for the report. Do you know what is the official replacement method ?

**Comment by electronicLight** [comment]
The official documentation (the link I sent) suggests to use the method angleDelta() for both delta() method and orientation attribute.

**Comment by rougier** [comment]
It is not clear to me. From what I've read, the `angleDelta` really measure the amount the (physical) mouse wheel has been rotated. Maybe we should use the  `pixelDelta` instead, no?

**Comment by electronicLight** [comment]
I don't think so. The method `pixelDelta` is not for all platforms. It's used to scroll text if I understood the docs. I've used `angleDelta` for while. It returns a `QPoint` where the `x / 120` counts how many "steps" was scrolled in horizontal direction and `y / 120` counts how many "steps" was scrolled in vertical direction.

Each mouse step (for the most mouse types) is 15º. Qt5 just defined 15º = 120 for some reason I don't know. I think it has something to do with the precision. Maybe Some mouses are good enough to trigger an event when the user scrolled 0.125º ( = 15º/120)... I'm really not sure. I'm not a Qt specialist.

Most mouses wheels can only scroll in vertical direction and I think we are only interested about the sign of `y`. Have a look at the code I wrote:
```
    def wheelEvent(self, event):
        if event.angleDelta().y() > 0:
            # perform the zoom in
            pass
        else:
            # perform the zoom out
            pass
```
I hope it helps. Sorry for my english (it's not my first language).

**Comment by rougier** [comment]
Thanks for the explanation, I didn't realize angleDelta was a Point (and not a scalar).

**Comment by electronicLight** [comment]
No problem. You're welcome!
